### ISSUE TITLE
1.21.1 launch error

### ISSUE THREAD

**Issue by rudde0** [cooffeeRequired/skJson#107]
```
[15:25:40] [Server thread/ERROR]: Error occurred while enabling SkJson v3.0.7 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at SkJson.jar/com.shanebeestudios.skbee.api.nbt.utils.nmsmappings.ReflectionMethod.<clinit>(ReflectionMethod.java:24) ~[SkJson.jar:?]
	at SkJson.jar/com.shanebeestudios.skbee.api.nbt.NBTContainer.<init>(NBTContainer.java:68) ~[SkJson.jar:?]
	at SkJson.jar/cz.coffee.skjson.api.Config.init(Config.java:284) ~[SkJson.jar:?]
	at SkJson.jar/cz.coffee.skjson.SkJson.onEnable(SkJson.java:39) ~[SkJson.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[purpur-1.21.1.jar:1.21.1-2323-4671e1e]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.21.1.jar:1.21.1-2323-4671e1e]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:654) ~[purpur-1.21.1.jar:1.21.1-2323-4671e1e]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:603) ~[purpur-1.21.1.jar:1.21.1-2323-4671e1e]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:757) ~[purpur-1.21.1.jar:1.21.1-2323-4671e1e]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:519) ~[purpur-1.21.1.jar:1.21.1-2323-4671e1e]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:366) ~[purpur-1.21.1.jar:1.21.1-2323-4671e1e]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1230) ~[purpur-1.21.1.jar:1.21.1-2323-4671e1e]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.1.jar:1.21.1-2323-4671e1e]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
	at SkJson.jar/com.shanebeestudios.skbee.api.nbt.utils.MinecraftVersion.getVersion(MinecraftVersion.java:111) ~[SkJson.jar:?]
	at SkJson.jar/com.shanebeestudios.skbee.api.nbt.utils.nmsmappings.ClassWrapper.<init>(ClassWrapper.java:79) ~[SkJson.jar:?]
	at SkJson.jar/com.shanebeestudios.skbee.api.nbt.utils.nmsmappings.ClassWrapper.<init>(ClassWrapper.java:73) ~[SkJson.jar:?]
	at SkJson.jar/com.shanebeestudios.skbee.api.nbt.utils.nmsmappings.ClassWrapper.<clinit>(ClassWrapper.java:21) ~[SkJson.jar:?]
	... 16 more
```

**Comment by cooffeeRequired** [comment]
Hello there, can you provide, more information, for e.g. skript version, server version tldr?

**Comment by rudde0** [comment]
Sure,

Skript version is 2.9.3
Server version is Purpur 1.21.1 b2323

I'm currently investigating the issue and I think its related with using outdated SkBee version.

Also we need to change NBTConvert#parseFromJson to use newer version of SkBee since its method params changed by SkBee.

**Comment by cooffeeRequired** [comment]
did you update the skjson to latest?

**Comment by rudde0** [comment]
Yes, also I tried to build from master

**Comment by cooffeeRequired** [comment]
Same issue right?

**Comment by rudde0** [comment]
Yes

**Comment by cooffeeRequired** [comment]
can you provide what expression or effect you run off?

**Comment by rudde0** [comment]
This error shows up on server boot and skJson disables itself, sorry I should said this in first place.

**Comment by cooffeeRequired** [comment]
that's wierd cause i already trying that, but in booted fine

**Comment by rudde0** [comment]
Is there any chance by classes of SkBee and skJson conflicting?

I also use SkBee 3.6.1.

**Comment by cooffeeRequired** [comment]
![image](https://github.com/user-attachments/assets/0274f829-b0c9-44ee-8a3d-bc6bf372010e)
![image](https://github.com/user-attachments/assets/dfe39c6c-1d1e-46a4-bf43-d74a57a869ea)

**Comment by cooffeeRequired** [comment]
```
[15:00:31 INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[15:00:33 INFO]: Loaded 1290 recipes
[15:00:34 INFO]: Loaded 1399 advancements
[15:00:34 INFO]: Starting minecraft server version 1.21.1
[15:00:34 INFO]: Loading properties
[15:00:34 INFO]: This server is running Purpur version 1.21.1-2324-ver/1.21.1@e12a4de (2024-10-09T23:26:12Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
[15:00:35 INFO]: [spark] This server bundles the spark profiler. For more information please visit https://docs.papermc.io/paper/profiling
[15:00:35 INFO]: Server Ping Player Sample Count: 12
[15:00:35 INFO]: Using 4 threads for Netty based IO
[15:00:36 INFO]: [ChunkTaskScheduler] Chunk system is using 1 I/O threads, 6 worker threads, and population gen parallelism of 6 threads
[15:00:36 WARN]: [Pufferfish] Will not enable SIMD! These optimizations are only safely supported on Java 17-21.
[15:00:36 INFO]: Default game type: SURVIVAL
[15:00:36 INFO]: Generating keypair
[15:00:36 INFO]: Starting Minecraft server on *:25565
[15:00:36 INFO]: Using default channel type
[15:00:36 INFO]: Paper: Using Java compression from Velocity.
[15:00:36 INFO]: Paper: Using Java cipher from Velocity.
[15:00:36 WARN]: [org.bukkit.craftbukkit.legacy.CraftLegacy] Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
[15:00:42 WARN]: Legacy plugin SkriptHubDocsTool v1.7 does not specify an api-version.
[15:00:42 INFO]: [SpigotLibraryLoader] [skript-mail] Loading 10 libraries... please wait
[15:00:42 INFO]: [SpigotLibraryLoader] [skript-mail] Loaded library C:\Users\nexti\Desktop\projects\mc-developing\libraries\org\jetbrains\kotlin\kotlin-gradle-plugin\1.9.22\kotlin-gradle-plugin-1.9.22.jar
[15:00:42 INFO]: [SpigotLibraryLoader] [skript-mail] Loaded library C:\Users\nexti\Desktop\projects\mc-developing\libraries\org\jetbrains\kotlin\kotlin-gradle-plugin-api\1.9.22\kotlin-gradle-plugin-api-1.9.22.jar
[15:00:42 INFO]: [SpigotLibraryLoader] [skript-mail] Loaded library C:\Users\nexti\Desktop\projects\mc-developing\libraries\org\jetbrains\kotlin\kotlin-gradle-plugin-annotations\1.9.22\kotlin-gradle-plugin-annotations-1.9.22.jar
[15:00:42 INFO]: [SpigotLibraryLoader] [skript-mail] Loaded library C:\Users\nexti\Desktop\projects\mc-developing\libraries\org\jetbrains\kotlin\kotlin-native-utils\1.9.22\kotlin-native-utils-1.9.22.jar 
[15:00:42 INFO]: [SpigotLibraryLoader] [skript-mail] Loaded library C:\Users\nexti\Desktop\projects\mc-developing\libraries\org\jetbrains\kotlin\kotlin-project-model\1.9.22\kotlin-project-model-1.9.22.jar
[15:00:42 INFO]: [SpigotLibraryLoader] [skript-mail] Loaded library C:\Users\nexti\Desktop\projects\mc-developing\libraries\org\jetbrains\kotlin\kotlin-tooling-core\1.9.22\kotlin-tooling-core-1.9.22.jar 
[15:00:42 INFO]: [SpigotLibraryLoader] [skript-mail] Loaded library C:\Users\nexti\Desktop\projects\mc-developing\libraries\org\jetbrains\kotlin\kotlin-gradle-plugin-model\1.9.22\kotlin-gradle-plugin-model-1.9.22.jar
[15:00:42 INFO]: [SpigotLibraryLoader] [skript-mail] Loaded library C:\Users\nexti\Desktop\projects\mc-developing\libraries\org\jetbrains\kotlin\kotlin-gradle-plugin-idea\1.9.22\kotlin-gradle-plugin-idea-1.9.22.jar
[15:00:42 INFO]: [SpigotLibraryLoader] [skript-mail] Loaded library C:\Users\nexti\Desktop\projects\mc-developing\libraries\org\jetbrains\kotlin\kotlin-gradle-plugin-idea-proto\1.9.22\kotlin-gradle-plugin-idea-proto-1.9.22.jar
[15:00:42 INFO]: [SpigotLibraryLoader] [skript-mail] Loaded library C:\Users\nexti\Desktop\projects\mc-developing\libraries\org\jetbrains\kotlin\kotlin-util-klib\1.9.22\kotlin-util-klib-1.9.22.jar       
[15:00:42 INFO]: [SpigotLibraryLoader] [skript-mail] Loaded library C:\Users\nexti\Desktop\projects\mc-developing\libraries\org\jetbrains\kotlin\kotlin-util-io\1.9.22\kotlin-util-io-1.9.22.jar
[15:00:42 INFO]: [SpigotLibraryLoader] [skript-mail] Loaded library C:\Users\nexti\Desktop\projects\mc-developing\libraries\org\jetbrains\kotlin\kotlin-klib-commonizer-api\1.9.22\kotlin-klib-commonizer-api-1.9.22.jar
[15:00:42 INFO]: [SpigotLibraryLoader] [skript-mail] Loaded library C:\Users\nexti\Desktop\projects\mc-developing\libraries\org\jetbrains\kotlin\kotlin-build-tools-api\1.9.22\kotlin-build-tools-api-1.9.22.jar
[15:00:42 INFO]: [SpigotLibraryLoader] [skript-mail] Loaded library C:\Users\nexti\Desktop\projects\mc-developing\libraries\org\jetbrains\kotlin\kotlin-compiler-embeddable\1.9.22\kotlin-compiler-embeddable-1.9.22.jar
[15:00:42 INFO]: [SpigotLibraryLoader] [skript-mail] Loaded library C:\Users\nexti\Desktop\projects\mc-developing\libraries\org\jetbrains\kotlin\kotlin-daemon-embeddable\1.9.22\kotlin-daemon-embeddable-1.9.22.jar
[15:00:42 INFO]: [SpigotLibraryLoader] [skript-mail] Loaded library C:\Users\nexti\Desktop\projects\mc-developing\libraries\org\jetbrains\intellij\deps\trove4j\1.0.20200330\trove4j-1.0.20200330.jar      
[15:00:42 INFO]: [SpigotLibraryLoader] [skript-mail] Loaded library C:\Users\nexti\Desktop\projects\mc-developing\libraries\org\jetbrains\kotlin\kotlin-android-extensions\1.9.22\kotlin-android-extensions-1.9.22.jar
[15:00:42 INFO]: [SpigotLibraryLoader] [skript-mail] Loaded library C:\Users\nexti\Desktop\projects\mc-developing\libraries\org\jetbrains\kotlin\kotlin-compiler-runner\1.9.22\kotlin-compiler-runner-1.9.22.jar
[15:00:42 INFO]: [SpigotLibraryLoader] [skript-mail] Loaded library C:\Users\nexti\Desktop\projects\mc-developing\libraries\org\jetbrains\kotlin\kotlin-daemon-client\1.9.22\kotlin-daemon-client-1.9.22.jar
[15:00:42 INFO]: [SpigotLibraryLoader] [skript-mail] Loaded library C:\Users\nexti\Desktop\projects\mc-developing\libraries\org\jetbrains\kotlin\kotlin-scripting-compiler-embeddable\1.9.22\kotlin-scripting-compiler-embeddable-1.9.22.jar
[15:00:42 INFO]: [SpigotLibraryLoader] [skript-mail] Loaded library C:\Users\nexti\Desktop\projects\mc-developing\libraries\org\jetbrains\kotlin\kotlin-scripting-compiler-impl-embeddable\1.9.22\kotlin-scripting-compiler-impl-embeddable-1.9.22.jar
[15:00:42 INFO]: [SpigotLibraryLoader] [skript-mail] Loaded library C:\Users\nexti\Desktop\projects\mc-developing\libraries\org\jetbrains\kotlin\kotlin-scripting-common\1.9.22\kotlin-scripting-common-1.9.22.jar
[15:00:42 INFO]: [SpigotLibraryLoader] [skript-mail] Loaded library C:\Users\nexti\Desktop\projects\mc-developing\libraries\org\jetbrains\kotlin\kotlin-scripting-jvm\1.9.22\kotlin-scripting-jvm-1.9.22.jar
[15:00:42 INFO]: [SpigotLibraryLoader] [skript-mail] Loaded library C:\Users\nexti\Desktop\projects\mc-developing\libraries\org\jetbrains\kotlinx\kotlinx-coroutines-core\1.8.0\kotlinx-coroutines-core-1.8.0.jar
[15:00:42 INFO]: [SpigotLibraryLoader] [skript-mail] Loaded library C:\Users\nexti\Desktop\projects\mc-developing\libraries\org\jetbrains\kotlinx\kotlinx-coroutines-core-jvm\1.8.0\kotlinx-coroutines-core-jvm-1.8.0.jar
[15:00:42 INFO]: [SpigotLibraryLoader] [skript-mail] Loaded library C:\Users\nexti\Desktop\projects\mc-developing\libraries\org\jetbrains\annotations\23.0.0\annotations-23.0.0.jar
[15:00:42 INFO]: [SpigotLibraryLoader] [skript-mail] Loaded library C:\Users\nexti\Desktop\projects\mc-developing\libraries\org\jetbrains\kotlin\kotlin-stdlib\1.9.21\kotlin-stdlib-1.9.21.jar
[15:00:42 INFO]: [SpigotLibraryLoader] [skript-mail] Loaded library C:\Users\nexti\Desktop\projects\mc-developing\libraries\com\sun\activation\jakarta.activation\2.0.1\jakarta.activation-2.0.1.jar       
[15:00:42 INFO]: [SpigotLibraryLoader] [skript-mail] Loaded library C:\Users\nexti\Desktop\projects\mc-developing\libraries\com\sun\mail\jakarta.mail\2.0.1\jakarta.mail-2.0.1.jar
[15:00:42 INFO]: [SpigotLibraryLoader] [skript-mail] Loaded library C:\Users\nexti\Desktop\projects\mc-developing\libraries\jakarta\xml\bind\jakarta.xml.bind-api\4.0.1\jakarta.xml.bind-api-4.0.1.jar     
[15:00:42 INFO]: [SpigotLibraryLoader] [skript-mail] Loaded library C:\Users\nexti\Desktop\projects\mc-developing\libraries\jakarta\activation\jakarta.activation-api\2.1.2\jakarta.activation-api-2.1.2.jar
[15:00:42 INFO]: [SpigotLibraryLoader] [skript-mail] Loaded library C:\Users\nexti\Desktop\projects\mc-developing\libraries\com\sanctionco\jmail\jmail\1.6.2\jmail-1.6.2.jar
[15:00:42 INFO]: [SpigotLibraryLoader] [skript-mail] Loaded library C:\Users\nexti\Desktop\projects\mc-developing\libraries\com\pivovarit\throwing-function\1.5.1\throwing-function-1.5.1.jar
[15:00:42 INFO]: [SpigotLibraryLoader] [skript-mail] Loaded library C:\Users\nexti\Desktop\projects\mc-developing\libraries\org\simplejavamail\simple-java-mail\8.6.3\simple-java-mail-8.6.3.jar
[15:00:42 INFO]: [SpigotLibraryLoader] [skript-mail] Loaded library C:\Users\nexti\Desktop\projects\mc-developing\libraries\com\github\bbottema\jetbrains-runtime-annotations\1.0.1\jetbrains-runtime-annotations-1.0.1.jar
[15:00:42 INFO]: [SpigotLibraryLoader] [skript-mail] Loaded library C:\Users\nexti\Desktop\projects\mc-developing\libraries\org\slf4j\slf4j-api\1.7.36\slf4j-api-1.7.36.jar
[15:00:42 INFO]: [SpigotLibraryLoader] [skript-mail] Loaded library C:\Users\nexti\Desktop\projects\mc-developing\libraries\org\simplejavamail\core-module\8.6.3\core-module-8.6.3.jar
[15:00:42 INFO]: [SpigotLibraryLoader] [skript-mail] Loaded library C:\Users\nexti\Desktop\projects\mc-developing\libraries\jakarta\mail\jakarta.mail-api\2.1.2\jakarta.mail-api-2.1.2.jar
[15:00:42 INFO]: [SpigotLibraryLoader] [skript-mail] Loaded library C:\Users\nexti\Desktop\projects\mc-developing\libraries\org\eclipse\angus\angus-mail\2.0.2\angus-mail-2.0.2.jar
[15:00:42 INFO]: [SpigotLibraryLoader] [skript-mail] Loaded library C:\Users\nexti\Desktop\projects\mc-developing\libraries\org\eclipse\angus\angus-activation\2.0.1\angus-activation-2.0.1.jar
[15:00:42 INFO]: [SpigotLibraryLoader] [SkJson] Loading 2 libraries... please wait
[15:00:43 INFO]: [SpigotLibraryLoader] [SkJson] Loaded library C:\Users\nexti\Desktop\projects\mc-developing\libraries\org\glassfish\jersey\core\jersey-server\2.34\jersey-server-2.34.jar
[15:00:43 INFO]: [SpigotLibraryLoader] [SkJson] Loaded library C:\Users\nexti\Desktop\projects\mc-developing\libraries\org\glassfish\jersey\core\jersey-common\2.34\jersey-common-2.34.jar
[15:00:43 INFO]: [SpigotLibraryLoader] [SkJson] Loaded library C:\Users\nexti\Desktop\projects\mc-developing\libraries\org\glassfish\hk2\osgi-resource-locator\1.0.3\osgi-resource-locator-1.0.3.jar       
[15:00:43 INFO]: [SpigotLibraryLoader] [SkJson] Loaded library C:\Users\nexti\Desktop\projects\mc-developing\libraries\org\glassfish\jersey\core\jersey-client\2.34\jersey-client-2.34.jar
[15:00:43 INFO]: [SpigotLibraryLoader] [SkJson] Loaded library C:\Users\nexti\Desktop\projects\mc-developing\libraries\jakarta\ws\rs\jakarta.ws.rs-api\2.1.6\jakarta.ws.rs-api-2.1.6.jar
[15:00:43 INFO]: [SpigotLibraryLoader] [SkJson] Loaded library C:\Users\nexti\Desktop\projects\mc-developing\libraries\jakarta\annotation\jakarta.annotation-api\1.3.5\jakarta.annotation-api-1.3.5.jar    
[15:00:43 INFO]: [SpigotLibraryLoader] [SkJson] Loaded library C:\Users\nexti\Desktop\projects\mc-developing\libraries\org\glassfish\hk2\external\jakarta.inject\2.6.1\jakarta.inject-2.6.1.jar
[15:00:43 INFO]: [SpigotLibraryLoader] [SkJson] Loaded library C:\Users\nexti\Desktop\projects\mc-developing\libraries\jakarta\validation\jakarta.validation-api\2.0.2\jakarta.validation-api-2.0.2.jar    
[15:00:43 INFO]: [SpigotLibraryLoader] [SkJson] Loaded library C:\Users\nexti\Desktop\projects\mc-developing\libraries\org\eclipse\jetty\jetty-client\12.0.1\jetty-client-12.0.1.jar
[15:00:43 INFO]: [SpigotLibraryLoader] [SkJson] Loaded library C:\Users\nexti\Desktop\projects\mc-developing\libraries\org\eclipse\jetty\jetty-http\12.0.1\jetty-http-12.0.1.jar
[15:00:43 INFO]: [SpigotLibraryLoader] [SkJson] Loaded library C:\Users\nexti\Desktop\projects\mc-developing\libraries\org\eclipse\jetty\jetty-util\12.0.1\jetty-util-12.0.1.jar
[15:00:43 INFO]: [SpigotLibraryLoader] [SkJson] Loaded library C:\Users\nexti\Desktop\projects\mc-developing\libraries\org\eclipse\jetty\jetty-io\12.0.1\jetty-io-12.0.1.jar
[15:00:43 INFO]: [SpigotLibraryLoader] [SkJson] Loaded library C:\Users\nexti\Desktop\projects\mc-developing\libraries\org\eclipse\jetty\jetty-alpn-client\12.0.1\jetty-alpn-client-12.0.1.jar
[15:00:43 INFO]: [SpigotLibraryLoader] [SkJson] Loaded library C:\Users\nexti\Desktop\projects\mc-developing\libraries\org\slf4j\slf4j-api\2.0.7\slf4j-api-2.0.7.jar
[15:00:43 INFO]: [Skript] Loading server plugin Skript v2.9.3
[15:00:43 INFO]: [Skript Hub Docs Tool] Loading server plugin SkriptHubDocsTool v1.7
[15:00:43 INFO]: [skript-mail] Loading server plugin SkriptMail v1.2
[15:00:43 INFO]: [SkJson] Loading server plugin SkJson v4.0.1
[15:00:43 INFO]: [SkBee] Loading server plugin SkBee v3.6.1
[15:00:43 INFO]: Server permissions file permissions.yml is empty, ignoring it
[15:00:43 INFO]: Preparing level "world"
[15:00:44 INFO]: Preparing start region for dimension minecraft:overworld
[15:00:45 INFO]: Time elapsed: 1045 ms
[15:00:45 INFO]: Preparing start region for dimension minecraft:the_nether
[15:00:45 INFO]: Time elapsed: 83 ms
[15:00:45 INFO]: Preparing start region for dimension minecraft:the_end
[15:00:45 INFO]: Time elapsed: 60 ms
[15:00:45 INFO]: [Skript] Enabling Skript v2.9.3
[15:00:47 INFO]: [Skript] You're currently running the latest stable version of Skript.
[15:00:56 INFO]: [Skript] Loaded 233074 aliases in 10041ms
[15:00:58 INFO]: [Skript]  ~ created by & © Peter Güttinger aka Njol ~
[15:00:58 INFO]: [Skript Hub Docs Tool] Enabling SkriptHubDocsTool v1.7*
[15:00:58 INFO]: [Skript Hub Docs Tool] For development servers only! Do not run this in production!
[15:00:58 INFO]: [Skript Hub Docs Tool] Skript Hub Docs Tool Enabled
[15:00:58 INFO]: [skript-mail] Enabling SkriptMail v1.2
[15:00:58 INFO]: [ skript-mail info ] Skript was found and hooked.
[15:00:58 INFO]: [ skript-mail info ] Metrics was hooked successfully
[15:00:58 INFO]: [ skript-mail info ] config.yml was loaded successfully.
[15:00:58 INFO]: [ skript-mail info ] templates/main.html was loaded successfully.
[15:00:58 INFO]: [ skript-mail ] Plugin was enabled successfully.
[15:00:58 INFO]: [SkJson] Enabling SkJson v4.0.1
[15:00:58 INFO]: [SkJson] NBTAPI  Was loaded successfully.
[15:00:58 INFO]: [SkJson] Metrics  Was loaded successfully.
[15:00:58 INFO]: [SkJson] Skript was found and initialized.
[15:00:58 INFO]: [SkJson] JsonWatcher was initialized.
[15:00:59 INFO]: [SkJson] You're running on last stable version. 4.0.1v.
[15:00:59 INFO]: [SkJson] Requests : GET request was send to 'https://api.github.com/repositories/555255955/releases/latest' and takes 00h 00m 00s.583ms'583000μs
[15:00:59 INFO]: [SkJson] Registered elements..
[15:00:59 INFO]: [SkJson]    - Registered Sections 1
[15:00:59 INFO]: [SkJson]    - Registered Events 1
[15:00:59 INFO]: [SkJson]    - Registered Structures 0
[15:00:59 INFO]: [SkJson]    - Registered Functions 4
[15:00:59 INFO]: [SkJson]    - Registered Effects 10
[15:00:59 INFO]: [SkJson]    - Registered Expressions 20
[15:00:59 INFO]: [SkJson]    - Registered Conditions 5
[15:00:59 INFO]: [SkJson] Hurray! SkJson is enabled.
[15:00:59 INFO]: [SkBee] Enabling SkBee v3.6.1
[15:00:59 INFO]: [SkBee] Loading NBTApi...
[15:00:59 INFO]: [SkBee] [NBTAPI] Found Minecraft: 1.21.1! Trying to find NMS support
[15:00:59 INFO]: [SkBee] [NBTAPI] NMS support 'MC1_21_R1' loaded!
[15:00:59 INFO]: [SkBee] Successfully loaded NBTApi!
[15:01:00 INFO]: [SkBee] NBT Elements successfully loaded
[15:01:00 INFO]: [SkBee] Text Component Elements successfully loaded
[15:01:00 INFO]: [SkBee] Advancement Elements successfully loaded
[15:01:00 INFO]: [SkBee] BossBar Elements successfully loaded
[15:01:00 INFO]: [SkBee] Bound Elements successfully loaded
[15:01:00 INFO]: [SkBee] Damage Source elements successfully loaded
[15:01:00 INFO]: [SkBee] Display Entity elements successfully loaded
[15:01:00 INFO]: [SkBee] Fishing elements successfully loaded
[15:01:00 INFO]: [SkBee] Game Event Elements successfully loaded
[15:01:00 INFO]: [SkBee] Item Component Elements successfully loaded
[15:01:00 INFO]: [SkBee] Particle Elements successfully loaded
[15:01:00 INFO]: [SkBee] RayTrace elements successfully loaded
[15:01:00 INFO]: [SkBee] Recipe Elements successfully loaded
[15:01:00 INFO]: [SkBee] Scoreboard Elements successfully loaded
[15:01:00 INFO]: [SkBee] Scoreboard Objective Elements successfully loaded
[15:01:00 INFO]: [SkBee] Statistic Elements successfully loaded
[15:01:00 INFO]: [SkBee] Structure Elements successfully loaded
[15:01:00 INFO]: [SkBee] Minecraft Tag elements successfully loaded
[15:01:00 INFO]: [SkBee] Team Elements successfully loaded
[15:01:00 INFO]: [SkBee] Tick Manager elements successfully loaded
[15:01:00 INFO]: [SkBee] Villager Elements successfully loaded
[15:01:00 INFO]: [SkBee] Virtual Furnace Elements disabled via config
[15:01:00 INFO]: [SkBee] World Border Elements successfully loaded
[15:01:00 INFO]: [SkBee] World Creator Elements successfully loaded
[15:01:00 INFO]: [SkBee] Chunk Generator Elements successfully loaded
[15:01:00 INFO]: [SkBee] Loaded (427) elements:
[15:01:00 INFO]: [SkBee]  - 56 events
[15:01:00 INFO]: [SkBee]  - 70 effects
[15:01:00 INFO]: [SkBee]  - 259 expressions
[15:01:00 INFO]: [SkBee]  - 27 conditions
[15:01:00 INFO]: [SkBee]  - 15 sections
[15:01:00 INFO]: [SkBee] Checking for update...
[15:01:00 INFO]: [SkBee] Plugin is up to date!
[15:01:00 INFO]: [SkBee] Successfully enabled v3.6.1 in 1,30 seconds
[15:01:00 INFO]: [spark] Starting background profiler...
[15:01:00 INFO]: [spark] The async-profiler engine is not supported for your os/arch (windows11/amd64), so the built-in Java engine will be used instead.
[15:01:01 INFO]: Done preparing level "world" (17.399s)
[15:01:01 INFO]: Running delayed init tasks
[15:01:01 INFO]: [Skript] Loading variables...
[15:01:01 INFO]: [Skript] Loaded 4 variables in 0.0 seconds
[15:01:01 INFO]: [Skript] All scripts loaded without errors.
[15:01:01 INFO]: [Skript] Loaded 1 script with a total of 2 structures in 0.08 seconds
[15:01:01 INFO]: [Skript] Finished loading.
[15:01:01 INFO]: Done (36.759s)! For help, type "help"
[15:01:01 INFO]: [SkriptMail] Trying established connection $0 EmailService(serviceId='gmail', properties={mail.imap.ssl.enable=true, mail.imap.host=imap.gmail.com, mail.smtp.port=587, mail.imap.connectionpoolsize=5, mail.smtp.auth=true, mail.smtp.starttls.enable=true, mail.imap.port=993, mail.smtp.host=smtp.gmail.com, mail.imap.partialfetch=true}, usernameOrEmail='nextikczcz@gmail.com', address='Jorgeee;testing@gmail.com', host=EmailHost(name=GMAIL, smtpHost=smtp.gmail.com, smtpPort=587, imapHost=imap.gmail.com, imapPort=993, sslAllowed=true, tlsAllowed=true))
[15:01:01 INFO]: [SkriptMail] [SMTP] connection status $0 true $1 EmailService(serviceId='gmail', properties={mail.imap.ssl.enable=true, mail.imap.host=imap.gmail.com, mail.smtp.port=587, mail.imap.connectionpoolsize=5, mail.smtp.auth=true, mail.smtp.starttls.enable=true, mail.imap.port=993, mail.smtp.host=smtp.gmail.com, mail.imap.partialfetch=true}, usernameOrEmail='nextikczcz@gmail.com', address='Jorgeee;testing@gmail.com', host=EmailHost(name=GMAIL, smtpHost=smtp.gmail.com, smtpPort=587, imapHost=imap.gmail.com, imapPort=993, sslAllowed=true, tlsAllowed=true))
[15:01:03 INFO]: [SkriptMail] [IMAP] connection status $0 true $1
[15:01:03 INFO]: [SkriptMail] Trying register mailbox !$ 'gmail'
[15:01:03 INFO]: [SkriptMail] Fetching emails... cz.coffeerequired.skriptmail.api.email.EmailMailbox@2a1c9771, INBOX
[15:01:03 INFO]: [SkriptMail] Task applied $0 cz.coffeerequired.skriptmail.api.email.EmailMailbox$Companion$register$1$1$1$$Lambda/0x000002ba638acb20@4397c7f7 $1 cz.coffeerequired.skriptmail.api.email.EmailMailbox@2a1c9771
[15:01:04 INFO]: [SkriptMail] Mailbox registered for service $0 cz.coffeerequired.skriptmail.api.email.EmailMailbox$Companion@195025a, $1 gmail
[15:01:04 INFO]: [SkriptMail] Mailbox registered successfully. $0 cz.coffeerequired.skriptmail.api.email.EmailMailbox@2a1c9771 $1 'gmail'
[15:01:04 INFO]: [SkriptMail] Mailbox bind event. $0 cz.coffeerequired.skriptmail.api.email.EmailMailbox@2a1c9771 $1 'gmail' $2 cz.coffeerequired.skriptmail.api.email.BukkitEmailMessageEvent@48b31af8    
[15:01:04 INFO]: [SkriptMail] Mailbox opened and folder in use $0 cz.coffeerequired.skriptmail.api.email.EmailMailbox@2a1c9771, $1 INBOX
[15:01:04 INFO]: [SkriptMail] Runner for repeating task registered successfully $0 io.papermc.paper.threadedregions.scheduler.FoliaAsyncScheduler$AsyncScheduledTask@579160ec
[15:01:04 INFO]: [SkriptMail] Service for id gmail was registered successfully
[15:01:04 INFO]: [SkriptMail] [INBOX] Mailbox was opened and successfully opened! cz.coffeerequired.skriptmail.api.email.EmailMailbox@2a1c9771 was registered successfully
[15:01:04 INFO]: [SkriptMail] Setting the 'READ_WRITE' flag to folder $0 cz.coffeerequired.skriptmail.api.email.EmailMailbox@2a1c9771.
[15:01:04 INFO]: [SkriptMail] Setting the 'READ_WRITE' successfully $0 cz.coffeerequired.skriptmail.api.email.EmailMailbox@2a1c9771.
[15:01:04 INFO]: [SkriptMail] Total connection time for [SMTP/IMAP] takes $0 2.986 seconds
> sk info
[15:01:13 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[15:01:13 INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[15:01:13 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[15:01:13 INFO]: [Skript] Server Version: 1.21.1-2324-e12a4de (MC: 1.21.1)
[15:01:13 INFO]: [Skript] Skript Version: 2.9.3 (skriptlang-github)
[15:01:13 INFO]: [Skript] Installed Skript Addons:
[15:01:13 INFO]: [Skript]  - SkJson v4.0.1
[15:01:13 INFO]: [Skript]  - SkBee v3.6.1 (https://github.com/ShaneBeee/SkBee)
[15:01:13 INFO]: [Skript]  - SkriptMail v1.2
[15:01:13 INFO]: [Skript] Installed dependencies: None
> pl
[15:01:14 INFO]: Paper Plugins: (0):
[15:01:14 INFO]: Bukkit Plugins: (5):
[15:01:14 INFO]:  - SkBee, SkJson, Skript, *SkriptHubDocsTool, SkriptMail
> about
[15:01:16 INFO]: Checking version, please wait...
[15:01:16 INFO]: Current Purpur Version: 1.21.1-2324-e12a4de (MC: 1.21.1)*
* You are 4 version(s) behind
Download the new version at: https://purpurmc.org/downloads
```

Not sure, but it's work fine

**Comment by rudde0** [comment]
weird. anyway plugin works fine after I upgrade SkBee version to 3.6.1, if plugin does work fine with older version of SkBee to you then we can close the issue. thank you

**Comment by cooffeeRequired** [comment]
Np, ill investigate that, will you notice later
