### ISSUE TITLE
Bug with Item-Data (Writable Book)

### ISSUE THREAD

**Issue by ExCorde** [cooffeeRequired/skJson#20]
**Describe the bug**
Massive Error with this code:

**To Reproduce**
```
On rightclick with writable book:
    set {_json} to json from event-item
    broadcast {_json} with pretty print
    give player {_json}
```

**Expected behavior**
The Book which was saved should be given to the player.

**Error-Message**
```
[12:15:33 ERROR]: [org.bukkit.configuration.serialization.ConfigurationSerialization] Could not call method 'public static org.bukkit.inventory.meta.ItemMeta org.bukkit.craftbukkit.v1_19_R2.inventory.CraftMetaItem$SerializableMeta.deserialize(java.util.Map) throws java.lang.Throwable' of class org.bukkit.craftbukkit.v1_19_R2.inventory.CraftMetaItem$SerializableMeta for deserialization
java.lang.IllegalArgumentException: custom-model-data(1.0) is not a valid class java.lang.Integer
        at org.bukkit.craftbukkit.v1_19_R2.inventory.CraftMetaItem$SerializableMeta.getObject(CraftMetaItem.java:237) ~[paper-1.19.3.jar:git-Paper-365]
        at org.bukkit.craftbukkit.v1_19_R2.inventory.CraftMetaItem.<init>(CraftMetaItem.java:529) ~[paper-1.19.3.jar:git-Paper-365]
        at org.bukkit.craftbukkit.v1_19_R2.inventory.CraftMetaBook.<init>(CraftMetaBook.java:129) ~[paper-1.19.3.jar:git-Paper-365]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
        at org.bukkit.craftbukkit.v1_19_R2.inventory.CraftMetaItem$SerializableMeta.deserialize(CraftMetaItem.java:201) ~[paper-1.19.3.jar:git-Paper-365]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeViaMethod(ConfigurationSerialization.java:85) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.serialization.ConfigurationSerialization.deserialize(ConfigurationSerialization.java:127) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(ConfigurationSerialization.java:207) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at cz.coffee.adapter.DefaultAdapters$TypeAdapter$Bukkit.deserialize(DefaultAdapters.java:789) ~[SkJson-2.6.21.jar:?]
        at cz.coffee.adapter.DefaultAdapters$TypeAdapter$Bukkit.deserialize(DefaultAdapters.java:783) ~[SkJson-2.6.21.jar:?]
        at cz.coffee.adapter.DefaultAdapters$TypeAdapter$Bukkit.deserialize(DefaultAdapters.java:766) ~[SkJson-2.6.21.jar:?]
        at ext.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76) ~[SkJson-2.6.21.jar:?]
        at ext.google.gson.Gson.fromJson(Gson.java:1227) ~[SkJson-2.6.21.jar:?]
        at ext.google.gson.Gson.fromJson(Gson.java:1329) ~[SkJson-2.6.21.jar:?]
        at ext.google.gson.Gson.fromJson(Gson.java:1271) ~[SkJson-2.6.21.jar:?]
        at cz.coffee.adapter.DefaultAdapters$3.fromJson(DefaultAdapters.java:436) ~[SkJson-2.6.21.jar:?]
        at cz.coffee.adapter.DefaultAdapters$3.fromJson(DefaultAdapters.java:148) ~[SkJson-2.6.21.jar:?]
        at cz.coffee.adapter.DefaultAdapters.assignFrom(DefaultAdapters.java:686) ~[SkJson-2.6.21.jar:?]
        at ch.njol.skript.classes.ChainedConverter.convert(ChainedConverter.java:55) ~[Skript-2.6.4.jar:?]
        at ch.njol.skript.registrations.Converters.convert(Converters.java:160) ~[Skript-2.6.4.jar:?]
        at ch.njol.skript.lang.Variable.getConverted(Variable.java:458) ~[Skript-2.6.4.jar:?]
        at ch.njol.skript.lang.Variable.getAll(Variable.java:680) ~[Skript-2.6.4.jar:?]
        at ch.njol.skript.lang.Variable.getArray(Variable.java:672) ~[Skript-2.6.4.jar:?]
        at ch.njol.skript.effects.EffChange.execute(EffChange.java:274) ~[Skript-2.6.4.jar:?]
        at ch.njol.skript.lang.Effect.run(Effect.java:50) ~[Skript-2.6.4.jar:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61) ~[Skript-2.6.4.jar:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89) ~[Skript-2.6.4.jar:?]
        at ch.njol.skript.lang.Trigger.execute(Trigger.java:56) ~[Skript-2.6.4.jar:?]
        at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:142) ~[Skript-2.6.4.jar:?]
        at ch.njol.skript.SkriptEventHandler.access$000(SkriptEventHandler.java:53) ~[Skript-2.6.4.jar:?]
        at ch.njol.skript.SkriptEventHandler$PriorityListener.lambda$new$0(SkriptEventHandler.java:71) ~[Skript-2.6.4.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:git-Paper-365]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:672) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:546) ~[paper-1.19.3.jar:git-Paper-365]
        at org.bukkit.craftbukkit.v1_19_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:503) ~[paper-1.19.3.jar:git-Paper-365]
        at org.bukkit.craftbukkit.v1_19_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:498) ~[paper-1.19.3.jar:git-Paper-365]
        at org.bukkit.craftbukkit.v1_19_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:493) ~[paper-1.19.3.jar:git-Paper-365]
        at org.bukkit.craftbukkit.v1_19_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:489) ~[paper-1.19.3.jar:git-Paper-365]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItem(ServerGamePacketListenerImpl.java:2017) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemPacket.handle(ServerboundUseItemPacket.java:32) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemPacket.a(ServerboundUseItemPacket.java:8) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.3.jar:git-Paper-365]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.3.jar:git-Paper-365]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.19.3.jar:git-Paper-365]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.3.jar:git-Paper-365]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.3.jar:git-Paper-365]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1289) ~[paper-1.19.3.jar:git-Paper-365]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[paper-1.19.3.jar:git-Paper-365]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-365]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by ExCorde** [comment]
JSON-File gets generated properly, btw. 
```
{
  "writable_letter": {
    "itemdata": {
      "==": "org.bukkit.inventory.ItemStack",
      "v": 3218,
      "type": "WRITABLE_BOOK",
      "meta": {
        "==": "ItemMeta",
        "meta-type": "BOOK",
        "display-name": "{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"white\",\"text\":\"Briefpapier\"}],\"text\":\"\"}",
        "custom-model-data": 1,
        "pages": [
          "Empfänger:\nNUTZE DIESE ZEILE\n\nZieladresse:  \nNUTZE DIESE ZEILE\n\nSender: \nNUTZE DIESE ZEILE\n\nTitel: \nNUTZE DIESE ZEILE"
        ]
      }
    }
  }
}
```

**Comment by ExCorde** [comment]
JSON-print gets generated properly, i guess.
```
{
  "==": "org.bukkit.inventory.ItemStack",
  "v": 3218,
  "type": "WRITABLE_BOOK",
  "meta": {
    "==": "ItemMeta",
    "meta-type": "BOOK",
    "display-name": "{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":"Briefpapier"}],"text":""}",
    "custom-model-data": 1,
    "pages": [
      "Empfänger:\nNUTZE DIESE ZEILE\n\nZieladresse:  \nNUTZE DIESE ZEILE\n\nSender: \nNUTZE DIESE ZEILE\n\nTitel: \nNUTZE DIESE ZEILE"
    ]
  }
}
```

**Comment by cooffeeRequired** [comment]
![image](https://user-images.githubusercontent.com/106232282/218163889-fb68d468-1efe-4bc9-be59-507dfb7474e3.png)
Fixed Already.

**Comment by ExCorde** [comment]
The problem was fixed and tested by community tester "ExCorde" on 10.02.2023 (21:45)
