### ISSUE TITLE
Error log for v1.1.3 (possible error in map function)

### ISSUE THREAD

**Issue by creptor** [cooffeeRequired/skJson#3]
Hi,

I tried the latest version, and it works great! but I also get an error on the console when loading a skript.
When my skript loads I get this:
```
[20:18:46] [Server thread/WARN]: ch.njol.skript.SkriptAPIException: Serializer of number must override newInstance(), canBeInstantiated() or mustSyncDeserialization() if its class does not have a nullary constructor
[20:18:46] [Server thread/WARN]: 	at Skript.jar//ch.njol.skript.classes.Serializer.newInstance(Serializer.java:79)
[20:18:46] [Server thread/WARN]: 	at Skript.jar//ch.njol.yggdrasil.Yggdrasil.newInstance(Yggdrasil.java:335)
[20:18:46] [Server thread/WARN]: 	at Skript.jar//ch.njol.yggdrasil.Yggdrasil.isSerializable(Yggdrasil.java:154)
[20:18:46] [Server thread/WARN]: 	at Skript.jar//ch.njol.yggdrasil.YggdrasilOutputStream.writeGenericObject(YggdrasilOutputStream.java:173)
[20:18:46] [Server thread/WARN]: 	at Skript.jar//ch.njol.yggdrasil.YggdrasilOutputStream.writeObject(YggdrasilOutputStream.java:249)
[20:18:46] [Server thread/WARN]: 	at Skript.jar//ch.njol.skript.registrations.Classes.serialize(Classes.java:724)
[20:18:46] [Server thread/WARN]: 	at Skript.jar//ch.njol.skript.variables.Variables.serialize(Variables.java:548)
[20:18:46] [Server thread/WARN]: 	at Skript.jar//ch.njol.skript.variables.Variables.serialize(Variables.java:542)
[20:18:46] [Server thread/WARN]: 	at Skript.jar//ch.njol.skript.variables.Variables.saveVariableChange(Variables.java:552)
[20:18:46] [Server thread/WARN]: 	at Skript.jar//ch.njol.skript.variables.Variables.setVariable(Variables.java:385)
[20:18:46] [Server thread/WARN]: 	at Skript.jar//ch.njol.skript.variables.Variables.setVariable(Variables.java:376)
[20:18:46] [Server thread/WARN]: 	at skript-gson-1.1.3.jar//cz.coffee.skriptgson.skript.effect.EffMapJsonToList.setVariable(EffMapJsonToList.java:131)
[20:18:46] [Server thread/WARN]: 	at skript-gson-1.1.3.jar//cz.coffee.skriptgson.skript.effect.EffMapJsonToList.map(EffMapJsonToList.java:124)
[20:18:46] [Server thread/WARN]: 	at skript-gson-1.1.3.jar//cz.coffee.skriptgson.skript.effect.EffMapJsonToList.lambda$JsonHandlerObject$0(EffMapJsonToList.java:94)
[20:18:46] [Server thread/WARN]: 	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
[20:18:46] [Server thread/WARN]: 	at skript-gson-1.1.3.jar//cz.coffee.skriptgson.skript.effect.EffMapJsonToList.JsonHandlerObject(EffMapJsonToList.java:94)
[20:18:46] [Server thread/WARN]: 	at skript-gson-1.1.3.jar//cz.coffee.skriptgson.skript.effect.EffMapJsonToList.map(EffMapJsonToList.java:110)
[20:18:46] [Server thread/WARN]: 	at skript-gson-1.1.3.jar//cz.coffee.skriptgson.skript.effect.EffMapJsonToList.lambda$JsonHandlerObject$0(EffMapJsonToList.java:94)
[20:18:46] [Server thread/WARN]: 	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
[20:18:46] [Server thread/WARN]: 	at skript-gson-1.1.3.jar//cz.coffee.skriptgson.skript.effect.EffMapJsonToList.JsonHandlerObject(EffMapJsonToList.java:94)
[20:18:46] [Server thread/WARN]: 	at skript-gson-1.1.3.jar//cz.coffee.skriptgson.skript.effect.EffMapJsonToList.mapE(EffMapJsonToList.java:84)
[20:18:46] [Server thread/WARN]: 	at skript-gson-1.1.3.jar//cz.coffee.skriptgson.skript.effect.EffMapJsonToList.execute(EffMapJsonToList.java:76)
[20:18:46] [Server thread/WARN]: 	at Skript.jar//ch.njol.skript.lang.Effect.run(Effect.java:50)
[20:18:46] [Server thread/WARN]: 	at Skript.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[20:18:46] [Server thread/WARN]: 	at Skript.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[20:18:46] [Server thread/WARN]: 	at Skript.jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:56)
[20:18:46] [Server thread/WARN]: 	at Skript.jar//ch.njol.skript.events.EvtScript.runTrigger(EvtScript.java:88)
[20:18:46] [Server thread/WARN]: 	at Skript.jar//ch.njol.skript.events.EvtScript.register(EvtScript.java:68)
[20:18:46] [Server thread/WARN]: 	at Skript.jar//ch.njol.skript.ScriptLoader.lambda$loadScript$7(ScriptLoader.java:811)
[20:18:46] [Server thread/WARN]: 	at Skript.jar//ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:834)
[20:18:46] [Server thread/WARN]: 	at Skript.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$4(ScriptLoader.java:526)
[20:18:46] [Server thread/WARN]: 	at Skript.jar//ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:418)
[20:18:46] [Server thread/WARN]: 	at Skript.jar//ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:434)
[20:18:46] [Server thread/WARN]: 	at Skript.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:525)
[20:18:46] [Server thread/WARN]: 	at Skript.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:469)
[20:18:46] [Server thread/WARN]: 	at Skript.jar//ch.njol.skript.Skript$1.run(Skript.java:786)
[20:18:46] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
[20:18:46] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[20:18:46] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1114)
[20:18:46] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
[20:18:46] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
```
I believe it's occurring in the map function because when I use.
`map json from {@json_text} to {json_data::*}`
It shows the error but works fine. Instead, if I use.
`map json from (json from file {@json_file}) to {json_data::*}`
It also works, but the colors are not parsed (sometimes?).

Example:
json as text (on skript)
![image](https://user-images.githubusercontent.com/3092157/200202559-bc4086c4-3538-43ec-ac8a-ae7bc295651a.png)
json as file
![image](https://user-images.githubusercontent.com/3092157/200202572-c37df13a-c1e7-48c0-8615-03c35c1a89e9.png)

I don’t know if it's my fault or not, but still wanted to post it here.

**Comment by cooffeeRequired** [comment]
Hi there 👋,
What is a @json? Wasn't that supposed to be {@json} ?

Thank you for all your reports so I can fix what I forgot.
Also please can you send replication? Your .sk file and also the json, according to the error message it is caused by numbers, as soon as I look at it

**Comment by cooffeeRequired** [comment]
Hello there! 👋

Bug fixed, I forgot to translate the character for colors. see screen 
![image](https://user-images.githubusercontent.com/106232282/200247481-6d3968fd-11dc-433d-91dc-9994b117a68c.png)

Sincerely Coffee 👋

**Comment by creptor** [comment]
Hi.

Tested v1.2.0 and the error is still there. Trying to reload skript triggers the error too.

Link to skript, json files and log: https://1drv.ms/u/s!AqREMVJVtSZrjMAAdZIKs9rfPnsWuw?e=cCMWXw
The map function is inside the load event ("on async load")

Also, now skript doesn't recognize the file load function:
```shell
[20:06:33] [Server thread/INFO]: [Skript] Loading variables...
[20:06:33] [Server thread/INFO]: [Skript] Loaded 5 variables in 0.0 seconds
[20:06:33] [Server thread/INFO]: [Skript] Line 46: (daily bonus.sk)
[20:06:33] [Server thread/INFO]:     Can't understand this condition/effect: map json from (json from file "plugins/Skript/scripts/daily bonus/custom_rewards_dates.json") to {bonus_data.important_dates_custom::*}
[20:06:33] [Server thread/INFO]:     Line: map json from (json from file "plugins/Skript/scripts/daily bonus/custom_rewards_dates.json") to {bonus_data.important_dates_custom::*}
[20:06:33] [Server thread/INFO]:  
[20:06:33] [Server thread/INFO]: [Skript] Line 48: (daily bonus.sk)
[20:06:33] [Server thread/INFO]:     Can't understand this condition/effect: map json from (json from file "plugins/Skript/scripts/daily bonus/default.json") to {bonus_data.default_lore::*}
[20:06:33] [Server thread/INFO]:     Line: map json from (json from file "plugins/Skript/scripts/daily bonus/default.json") to {bonus_data.default_lore::*}
```

**Comment by cooffeeRequired** [comment]
Hello.
I don't understand exactly what `@options` is without `{}`, are you sure it's supposed to be like that?

**Comment by creptor** [comment]
Oh, right. That was just a typo.

The `@options` does need to be enclosed with `{}` (fixed).

I still get the error though, with the functioning code provided.

**Comment by cooffeeRequired** [comment]
Hello, I am still unable to replicate this error.

**Comment by creptor** [comment]
I understand.

Will try to replicate on new instance and post results...

Maybe it's a plugin compatibility error...

**Comment by cooffeeRequired** [comment]
Good thank you for your cooperation, Sincerely coffee 👋

**Comment by creptor** [comment]
Error replicated correctly on instance (with only 1 test skript).

https://1drv.ms/u/s!AqREMVJVtSZrjMEEl0uGFz2OKggTRw?e=cLhRJx

Instance:
```
System Info: Java 19 (Java HotSpot(TM) 64-Bit Server VM 19.0.1+10-21) Host: Windows 11 10.0 (amd64)
Paper version git-Paper-265 (MC: 1.19.2)
Plugins:
Skript v2.6.3
skript-gson v1.1.3
```
----------------------
Note: skript-gson v1.2.0 should throw the additional error on [#issuecomment-1311048937](https://github.com/cooffeeRequired/skript-gson/issues/3#issuecomment-1311048937)

**Comment by cooffeeRequired** [comment]
Hi there, error was replicated, error occurred because the jsonMap effect it's old, so we will fix that on next release

**Comment by cooffeeRequired** [comment]
![image](https://user-images.githubusercontent.com/106232282/203027733-5bc2578e-d85c-4a8b-ab91-2bd611b15654.png)

Hi after reworking the whole MapJson File class, all fixed and bug free ^^ here is a snapshot directly from your test instance you sent me.

Fixed version: [_This_](https://github.com/cooffeeRequired/skript-gson/releases/tag/1.3.0)
And they also advise you to re-read the docs. [Here.](http://skripthub.net/docs/?addon=Skript-Gson)



**Sincerely coffee** 👋

Here I attach the files I used directly.
[daily bonus.zip](https://github.com/cooffeeRequired/skript-gson/files/10055669/daily.bonus.zip)
