### ISSUE TITLE
ItemStack enchants, meta broken

### ISSUE THREAD

**Issue by cooffeeRequired** [cooffeeRequired/skJson#39]
```
[19:35:22 WARN]: java.lang.NullPointerException: Cannot invoke "shaded.google.gson.JsonObject.entrySet()" because the return value of "shaded.google.gson.JsonObject.getAsJsonObject(String)" is null
[19:35:22 WARN]:        at skJson(2).jar//cz.coffee.core.adapters.Adapters$5.setEnchants(Adapters.java:178)
[19:35:22 WARN]:        at skJson(2).jar//cz.coffee.core.adapters.Adapters$5.fromJson(Adapters.java:225)
[19:35:22 WARN]:        at skJson(2).jar//cz.coffee.core.adapters.Adapters$5.fromJson(Adapters.java:173)
[19:35:22 WARN]:        at skJson(2).jar//cz.coffee.core.adapters.Adapters$7.lambda$fromJson$0(Adapters.java:582)
[19:35:22 WARN]:        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
[19:35:22 WARN]:        at skJson(2).jar//cz.coffee.core.adapters.Adapters$7.fromJson(Adapters.java:577)
[19:35:22 WARN]:        at skJson(2).jar//cz.coffee.core.adapters.Adapters$7.fromJson(Adapters.java:552)
[19:35:22 WARN]:        at skJson(2).jar//cz.coffee.core.utils.AdapterUtils.assignFrom(AdapterUtils.java:164)
[19:35:22 WARN]:        at Skript-2.7.0-beta1.jar//org.skriptlang.skript.lang.converter.Converters.convert(Converters.java:389)
[19:35:22 WARN]:        at Skript-2.7.0-beta1.jar//ch.njol.skript.lang.Variable.getConverted(Variable.java:488)
[19:35:22 WARN]:        at Skript-2.7.0-beta1.jar//ch.njol.skript.lang.Variable.getSingle(Variable.java:697)
[19:35:22 WARN]:        at Skript-2.7.0-beta1.jar//ch.njol.skript.effects.EffOpenInventory.execute(EffOpenInventory.java:106)
[19:35:22 WARN]:        at Skript-2.7.0-beta1.jar//ch.njol.skript.lang.Effect.run(Effect.java:50)
[19:35:22 WARN]:        at Skript-2.7.0-beta1.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:62)
[19:35:22 WARN]:        at Skript-2.7.0-beta1.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:90)
[19:35:22 WARN]:        at Skript-2.7.0-beta1.jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:52)
[19:35:22 WARN]:        at Skript-2.7.0-beta1.jar//ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:312)
[19:35:22 WARN]:        at Skript-2.7.0-beta1.jar//ch.njol.skript.command.ScriptCommand.lambda$execute$0(ScriptCommand.java:277)
[19:35:22 WARN]:        at Skript-2.7.0-beta1.jar//ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:282)
[19:35:22 WARN]:        at Skript-2.7.0-beta1.jar//ch.njol.skript.command.Commands.handleCommand(Commands.java:193)
[19:35:22 WARN]:        at Skript-2.7.0-beta1.jar//ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:152)
[19:35:22 WARN]:        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40)
[19:35:22 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
[19:35:22 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[19:35:22 WARN]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[19:35:22 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[19:35:22 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
[19:35:22 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2347)
[19:35:22 WARN]:        at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$21(PlayerConnection.java:2331)
[19:35:22 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)
[19:35:22 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[19:35:22 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[19:35:22 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[19:35:22 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[19:35:22 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1366)
[19:35:22 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197)
[19:35:22 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[19:35:22 WARN]:        at net.minecraft.server.MinecraftServer.bi(MinecraftServer.java:1343)
[19:35:22 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1336)
[19:35:22 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[19:35:22 WARN]:        at net.minecraft.server.MinecraftServer.i_(MinecraftServer.java:1314)
[19:35:22 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1202)
[19:35:22 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322)
[19:35:22 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by cooffeeRequired** [comment]
**Fixed jar**: -> [Fixed Inventory-SkJson.zip](https://github.com/cooffeeRequired/skJson/files/11040493/Fixed.Inventory-SkJson.zip)
