### ISSUE TITLE
Conflicting erros

### ISSUE THREAD

**Issue by Pumkinhead** [cooffeeRequired/skJson#65]
write {_json} to json file "plugins/Skript/jsonplayerdata/%{_p}'s uuid%"
When without ".json" yeets error:
java.lang.IllegalArgumentException: File must end with '.json'
	at cz.coffee.core.utils.JsonFile.<init>(JsonFile.java:15) ~[skJson-2.8.5.jar:?]
	at cz.coffee.skript.effects.EffWriteJsonFile.execute(EffWriteJsonFile.java:54) ~[skJson-2.8.5.jar:?]
	at ch.njol.skript.util.AsyncEffect.lambda$walk$1(AsyncEffect.java:60) ~[Skript-2.6.4.jar:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-411]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[patched_1.17.1.jar:git-Paper-411]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Paper-411]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[09:20:39] [Craft Scheduler Thread - 17 - Skript/WARN]: [Skript] Plugin Skript v2.6.4 generated an exception while executing task 27858
java.lang.IllegalArgumentException: File must end with '.json'
	at cz.coffee.core.utils.JsonFile.<init>(JsonFile.java:15) ~[skJson-2.8.5.jar:?]
	at cz.coffee.skript.effects.EffWriteJsonFile.execute(EffWriteJsonFile.java:54) ~[skJson-2.8.5.jar:?]
	at ch.njol.skript.util.AsyncEffect.lambda$walk$1(AsyncEffect.java:60) ~[Skript-2.6.4.jar:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-411]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[patched_1.17.1.jar:git-Paper-411]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Paper-411]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[09:20:39] [Craft Scheduler Thread - 16 - Skript/WARN]: [Skript] Plugin Skript v2.6.4 generated an exception while executing task 27857
java.lang.IllegalArgumentException: File must end with '.json'
	at cz.coffee.core.utils.JsonFile.<init>(JsonFile.java:15) ~[skJson-2.8.5.jar:?]
	at cz.coffee.skript.effects.EffWriteJsonFile.execute(EffWriteJsonFile.java:54) ~[skJson-2.8.5.jar:?]
	at ch.njol.skript.util.AsyncEffect.lambda$walk$1(AsyncEffect.java:60) ~[Skript-2.6.4.jar:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-411]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[patched_1.17.1.jar:git-Paper-411]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Paper-411]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

And when I add .json to everything this line:
map {_json} to {playerdata::%{_p}'s uuid%::*}
gives this error:
[06:00:56] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[06:00:56] [Server thread/ERROR]: #!#! 
[06:00:56] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[06:00:56] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[06:00:56] [Server thread/ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[06:00:56] [Server thread/ERROR]: #!#! Here is full list of them:
[06:00:56] [Server thread/ERROR]: #!#! skJson v2.8.5 (https://github.com/SkJsonTeam/skJson) skript-reflect v2.3 (https://github.com/TPGamesNL/skript-reflect) skript-gui v1.3 (https://github.com/APickledWalrus/skript-gui) DiSky v4.11.1 SkBee v2.11.0 (https://github.com/ShaneBeee/SkBee) 
[06:00:56] [Server thread/ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[06:00:56] [Server thread/ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[06:00:56] [Server thread/ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[06:00:56] [Server thread/ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[06:00:56] [Server thread/ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[06:00:56] [Server thread/ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[06:00:56] [Server thread/ERROR]: #!#! 
[06:00:56] [Server thread/ERROR]: #!#! Stack trace:
[06:00:56] [Server thread/ERROR]: #!#! java.lang.IllegalArgumentException: Event may not be null in non-simple VariableStrings!
[06:00:56] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.VariableString.toString(VariableString.java:365)
[06:00:56] [Server thread/ERROR]: #!#!     at skJson-2.8.5.jar//cz.coffee.skript.mapping.EffJsonToSkriptList.toString(EffJsonToSkriptList.java:52)
[06:00:56] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.Skript.exception(Skript.java:1737)
[06:00:56] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.Skript.exception(Skript.java:1560)
[06:00:56] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:100)
[06:00:56] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:56)
[06:00:56] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.function.ScriptFunction.execute(ScriptFunction.java:85)
[06:00:56] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.function.Function.execute(Function.java:129)
[06:00:56] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.function.FunctionReference.execute(FunctionReference.java:299)
[06:00:56] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.function.EffFunctionCall.execute(EffFunctionCall.java:52)
[06:00:56] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.Effect.run(Effect.java:50)
[06:00:56] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[06:00:56] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[06:00:56] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:56)
[06:00:56] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:142)
[06:00:56] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.SkriptEventHandler.access$000(SkriptEventHandler.java:53)
[06:00:56] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.SkriptEventHandler$PriorityListener.lambda$new$0(SkriptEventHandler.java:71)
[06:00:56] [Server thread/ERROR]: #!#!     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[06:00:56] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[06:00:56] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
[06:00:56] [Server thread/ERROR]: #!#!     at net.minecraft.server.players.PlayerList.postChunkLoadJoin(PlayerList.java:360)
[06:00:56] [Server thread/ERROR]: #!#!     at net.minecraft.server.players.PlayerList.lambda$placeNewPlayer$1(PlayerList.java:302)
[06:00:56] [Server thread/ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.tick(PlayerConnection.java:307)
[06:00:56] [Server thread/ERROR]: #!#!     at net.minecraft.network.NetworkManager.a(NetworkManager.java:555)
[06:00:56] [Server thread/ERROR]: #!#!     at net.minecraft.server.network.ServerConnection.c(ServerConnection.java:201)
[06:00:56] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1656)
[06:00:56] [Server thread/ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:490)
[06:00:56] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1483)
[06:00:56] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1282)
[06:00:56] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[06:00:56] [Server thread/ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[06:00:56] [Server thread/ERROR]: #!#! 
[06:00:56] [Server thread/ERROR]: #!#! Version Information:
[06:00:56] [Server thread/ERROR]: #!#!   Skript: 2.6.4
[06:00:56] [Server thread/ERROR]: #!#!     Flavor: skriptlang-github
[06:00:56] [Server thread/ERROR]: #!#!     Date: 17:14:25.041218900
[06:00:56] [Server thread/ERROR]: #!#!   Bukkit: 1.17.1-R0.1-SNAPSHOT
[06:00:56] [Server thread/ERROR]: #!#!   Minecraft: 1.17.1
[06:00:56] [Server thread/ERROR]: #!#!   Java: 17.0.7 (OpenJDK 64-Bit Server VM 17.0.7+7)
[06:00:56] [Server thread/ERROR]: #!#!   OS: Linux amd64 5.19.0-43-generic
[06:00:56] [Server thread/ERROR]: #!#! 
[06:00:56] [Server thread/ERROR]: #!#! Server platform: Paper
[06:00:56] [Server thread/ERROR]: #!#! 
[06:00:56] [Server thread/ERROR]: #!#! Current node: null
[06:00:56] [Server thread/ERROR]: #!#! Current item: Load(the player)
[06:00:56] [Server thread/ERROR]: #!#! Current trigger: join (simple event) (jsonplayerdata.sk, line 1)
[06:00:56] [Server thread/ERROR]: #!#! 
[06:00:56] [Server thread/ERROR]: #!#! Thread: Server thread
[06:00:56] [Server thread/ERROR]: #!#! 
[06:00:56] [Server thread/ERROR]: #!#! Language: english
[06:00:56] [Server thread/ERROR]: #!#! Link parse mode: STRICT
[06:00:56] [Server thread/ERROR]: #!#! 
[06:00:56] [Server thread/ERROR]: #!#! End of Error.
[06:00:56] [Server thread/ERROR]: #!#!

**Comment by cooffeeRequired** [comment]
Hello there i recommend you download 2.9 And skript 2.7+ with addon patcher, or 2.8.6 with skript 2.6+

**Comment by ghost** [comment]
![image](https://github.com/SkJsonTeam/skJson/assets/130649230/180f0310-00a2-4cbb-9baf-99d3b4676237)
This tells you that the file must end in .json, but you have no extension.
`write {_json} to json file "plugins/Script/jsonplayerdata/%{_p}'s uuid%"`
it should be
`write {_json} to json file "plugins/Script/jsonplayerdata/%{_p}'s uuid%.json"`
