### ISSUE TITLE
A random error

### ISSUE THREAD

**Issue by Pumkinhead** [cooffeeRequired/skJson#69]
[16:43:00 WARN]: [Skript] Plugin Skript v2.6.4 generated an exception while executing task 103
ch.njol.skript.SkriptAPIException: Serializer of number must override newInstance(), canBeInstantiated() or mustSyncDeserialization() if its class does not have a nullary constructor
at ch.njol.skript.classes.Serializer.newInstance(Serializer.java:79) ~[Skript-2.6.4.jar:?]
at ch.njol.yggdrasil.Yggdrasil.newInstance(Yggdrasil.java:335) ~[Skript-2.6.4.jar:?]
at ch.njol.yggdrasil.Yggdrasil.isSerializable(Yggdrasil.java:154) ~[Skript-2.6.4.jar:?]
at ch.njol.yggdrasil.YggdrasilOutputStream.writeGenericObject(YggdrasilOutputStream.java:173) ~[Skript-2.6.4.jar:?]
at ch.njol.yggdrasil.YggdrasilOutputStream.writeObject(YggdrasilOutputStream.java:249) ~[Skript-2.6.4.jar:?]
at ch.njol.skript.registrations.Classes.serialize(Classes.java:724) ~[Skript-2.6.4.jar:?]
at ch.njol.skript.variables.FlatFileStorage.save(FlatFileStorage.java:438) ~[Skript-2.6.4.jar:?]
at ch.njol.skript.variables.FlatFileStorage.save(FlatFileStorage.java:432) ~[Skript-2.6.4.jar:?]
at ch.njol.skript.variables.FlatFileStorage.saveVariables(FlatFileStorage.java:386) ~[Skript-2.6.4.jar:?]
at ch.njol.skript.variables.FlatFileStorage$1.run(FlatFileStorage.java:198) ~[Skript-2.6.4.jar:?]
at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-411]
at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[patched_1.17.1.jar:git-Paper-411]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Paper-411]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by cooffeeRequired** [comment]
Hello there, what version od SkJson do you using?
