### ISSUE TITLE
Cannot read the array length because the value is null

### ISSUE THREAD

**Issue by Pumkinhead** [cooffeeRequired/skJson#71]
Code:
function Load(p: offline player):
	set {_json} to json from file "plugins/Skript/jsonplayerdata/%{_p}'s uuid%.json"
	map json {_json} to {playerdata::%{_p}'s uuid%::*}
	send {playerdata::%{_p}'s uuid%::*}'s form to {_p}

Error:
[12:56:35 ERROR]: #!#! 
[12:56:35 ERROR]: #!#! [Skript] Severe Error:
[12:56:35 ERROR]: #!#! 
[12:56:35 ERROR]: #!#! Something went horribly wrong with Skript.
[12:56:35 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[12:56:35 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[12:56:35 ERROR]: #!#! Here is full list of them:
[12:56:35 ERROR]: #!#! skJson v2.8.6 (https://github.com/SkJsonTeam/skJson) skript-reflect v2.3 (https://github.com/TPGamesNL/skript-reflect) skript-gui v1.3 (https://github.com/APickledWalrus/skript-gui) DiSky v4.11.1 SkBee v2.11.0 (https://github.com/ShaneBeee/SkBee) 
[12:56:35 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[12:56:35 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[12:56:35 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[12:56:35 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[12:56:35 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[12:56:35 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[12:56:35 ERROR]: #!#! 
[12:56:35 ERROR]: #!#! Stack trace:
[12:56:35 ERROR]: #!#! java.lang.NullPointerException: Cannot read the array length because the return value of "com.mojang.authlib.yggdrasil.response.ProfileSearchResultsResponse.getProfiles()" is null
[12:56:35 ERROR]: #!#!     at com.mojang.authlib.yggdrasil.YggdrasilGameProfileRepository.findProfilesByNames(YggdrasilGameProfileRepository.java:59)
[12:56:35 ERROR]: #!#!     at com.destroystokyo.paper.profile.PaperGameProfileRepository.findProfilesByNames(PaperGameProfileRepository.java:44)
[12:56:35 ERROR]: #!#!     at net.minecraft.server.players.UserCache.a(UserCache.java:109)
[12:56:35 ERROR]: #!#!     at net.minecraft.server.players.UserCache.getProfile(UserCache.java:174)
[12:56:35 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_17_R1.CraftServer.getOfflinePlayer(CraftServer.java:1797)
[12:56:35 ERROR]: #!#!     at org.bukkit.Bukkit.getOfflinePlayer(Bukkit.java:1094)
[12:56:35 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.classes.data.BukkitClasses$18.parse(BukkitClasses.java:798)
[12:56:35 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.classes.data.BukkitClasses$18.parse(BukkitClasses.java:788)
[12:56:35 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.expressions.ExprParse.get(ExprParse.java:157)
[12:56:35 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:99)
[12:56:35 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.function.FunctionReference.execute(FunctionReference.java:289)
[12:56:35 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.function.EffFunctionCall.execute(EffFunctionCall.java:52)
[12:56:35 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.Effect.run(Effect.java:50)
[12:56:35 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[12:56:35 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[12:56:35 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.command.Commands.handleEffectCommand(Commands.java:290)
[12:56:35 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.command.Commands$3$1.call(Commands.java:220)
[12:56:35 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.command.Commands$3$1.call(Commands.java:217)
[12:56:35 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftFuture.run(CraftFuture.java:88)
[12:56:35 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[12:56:35 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1567)
[12:56:35 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:490)
[12:56:35 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1483)
[12:56:35 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1282)
[12:56:35 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[12:56:35 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[12:56:35 ERROR]: #!#! 
[12:56:35 ERROR]: #!#! Version Information:
[12:56:35 ERROR]: #!#!   Skript: 2.6.4
[12:56:35 ERROR]: #!#!     Flavor: skriptlang-github
[12:56:35 ERROR]: #!#!     Date: 17:14:25.041218900
[12:56:35 ERROR]: #!#!   Bukkit: 1.17.1-R0.1-SNAPSHOT
[12:56:35 ERROR]: #!#!   Minecraft: 1.17.1
[12:56:35 ERROR]: #!#!   Java: 17.0.7 (OpenJDK 64-Bit Server VM 17.0.7+7)
[12:56:35 ERROR]: #!#!   OS: Linux amd64 5.19.0-43-generic
[12:56:35 ERROR]: #!#! 
[12:56:35 ERROR]: #!#! Server platform: Paper
[12:56:35 ERROR]: #!#! 
[12:56:35 ERROR]: #!#! Current node: null
[12:56:35 ERROR]: #!#! Current item: Save("player" parsed as a offline player)
[12:56:35 ERROR]: #!#! 
[12:56:35 ERROR]: #!#! Thread: Server thread
[12:56:35 ERROR]: #!#! 
[12:56:35 ERROR]: #!#! Language: english
[12:56:35 ERROR]: #!#! Link parse mode: STRICT
[12:56:35 ERROR]: #!#! 
[12:56:35 ERROR]: #!#! End of Error.
[12:56:35 ERROR]: #!#!

**Comment by Pumkinhead** [comment]
The actual code is this:
set {_json} to {playerdata::%{_p}'s uuid%::*}'s form
	write {_json} to json file "plugins/Skript/jsonplayerdata/%{_p}'s uuid%.json"
	if {_b} = true:
		delete {playerdata::%{_p}'s uuid%::*}

**Comment by Pumkinhead** [comment]
```
set {_json} to {playerdata::%{_p}'s uuid%::*}'s form
	write {_json} to json file "plugins/Skript/jsonplayerdata/%{_p}'s uuid%.json"
	if {_b} = true:
		delete {playerdata::%{_p}'s uuid%::*}
```

**Comment by ghost** [comment]
Okey, let me see that-

**Comment by Pumkinhead** [comment]
So?

**Comment by cooffeeRequired** [comment]
I can't replicate the error, can we continue on discord with particular environment?

**Comment by ghost** [comment]
![image](https://github.com/SkJsonTeam/skJson/assets/130649230/52f34b44-b637-4100-a744-29ad2f934764)
**json file after write**
```json
{
  "level": 0,
  "location": {
    "==": "org.bukkit.Location",
    "world": "world_nether",
    "x": 16.621444812332303,
    "y": 33.0,
    "z": 14.293395368153341,
    "pitch": 25.199608,
    "yaw": -83.70821
  },
  "name": "_F0cus__"
}
```
**Skript**
```sh
command testPlayerdata:
	trigger:
		set {playerdata::%player's uuid%::name} to player's name
		set {playerdata::%player's uuid%::level} to player's level
		set {playerdata::%player's uuid%::location} to player's location
		send {playerdata::%player's uuid%::*} to console

command test:
	trigger:
		set {_json} to {playerdata::%player's uuid%::*}'s form
		write {_json} to json file "plugins/Skript/jsonplayerdata/%player's uuid%.json"
		if {_b} = true:
			delete {playerdata::%player's uuid%::*}
```
**Skript details**
```
[21:27:51 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[21:27:51 INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[21:27:51 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[21:27:51 INFO]: [Skript] Server Version: git-Paper-307 (MC: 1.19.2)
[21:27:51 INFO]: [Skript] Skript Version: 2.6.4
[21:27:51 INFO]: [Skript] Installed Skript Addons:
[21:27:51 INFO]: [Skript]  - skJson v2.8.6 (https://github.com/SkJsonTeam/skJson)
[21:27:51 INFO]: [Skript]  - skript-reflect v2.3 (https://github.com/TPGamesNL/skript-reflect)
[21:27:51 INFO]: [Skript]  - SkBee v2.16.1 (https://github.com/ShaneBeee/SkBee)
[21:27:51 INFO]: [Skript] Installed dependencies: None
```
**Server details**
```
[21:28:18 INFO]: This server is running Paper version git-Paper-307 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 476ef25)
You are running the latest version
```


Conclusion: Your problem cannot be replicate.

**Comment by Pumkinhead** [comment]
> I can't replicate the error, can we continue on discord with particular environment?

Whats the discord?

**Comment by ghost** [comment]
https://discord.com/invite/dsZq5Cs9fd
