### ISSUE TITLE
Error when getting item from json

### ISSUE THREAD

**Issue by envizar** [cooffeeRequired/skJson#72]
skJson Version: 2.9
Skript Version: 2.7.0
Minecraft Version: Paper 1.20.1

When getting as item, for example, 
```json
"==": "org.bukkit.inventory.ItemStack",
"v": 3465,
"meta": {
  "==": "ItemMeta",
  "meta-type": "UNSPECIFIC",
  "Damage": 3
},
"type": "DIAMOND_SWORD"
```
, it gives this error:

```
[20:45:05 ERROR]: [org.bukkit.configuration.serialization.ConfigurationSerialization] Could not call method 'public static org.bukkit.inventory.meta.ItemMeta org.bukkit.craftbukkit.v1_20_R1.inventory.CraftMetaItem$SerializableMeta.deserialize(java.util.Map) throws java.lang.Throwable' of class org.bukkit.craftbukkit.v1_20_R1.inventory.CraftMetaItem$SerializableMeta for deserialization
java.lang.IllegalArgumentException: Damage(3.0) is not a valid class java.lang.Integer
        at org.bukkit.craftbukkit.v1_20_R1.inventory.CraftMetaItem$SerializableMeta.getObject(CraftMetaItem.java:240) ~[paper-1.20.1.jar:git-Paper-174]
        at org.bukkit.craftbukkit.v1_20_R1.inventory.CraftMetaItem.<init>(CraftMetaItem.java:577) ~[paper-1.20.1.jar:git-Paper-174]
        at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:483) ~[?:?]
        at org.bukkit.craftbukkit.v1_20_R1.inventory.CraftMetaItem$SerializableMeta.deserialize(CraftMetaItem.java:204) ~[paper-1.20.1.jar:git-Paper-174]
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
        at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeViaMethod(ConfigurationSerialization.java:85) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.serialization.ConfigurationSerialization.deserialize(ConfigurationSerialization.java:127) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(ConfigurationSerialization.java:207) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at cz.coffee.skjson.skript.base.Converter$BukkitConverter.deserialize(Converter.java:548) ~[skJson-2.9.shaded(2).jar:?]
        at cz.coffee.skjson.skript.base.Converter$BukkitConverter.deserialize(Converter.java:534) ~[skJson-2.9.shaded(2).jar:?]
        at cz.coffee.api.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76) ~[skJson-2.9.shaded(2).jar:?]
        at cz.coffee.api.gson.Gson.fromJson(Gson.java:1227) ~[skJson-2.9.shaded(2).jar:?]
        at cz.coffee.api.gson.Gson.fromJson(Gson.java:1329) ~[skJson-2.9.shaded(2).jar:?]
        at cz.coffee.api.gson.Gson.fromJson(Gson.java:1271) ~[skJson-2.9.shaded(2).jar:?]
        at cz.coffee.skjson.skript.base.Converter$3.fromJson(Converter.java:403) ~[skJson-2.9.shaded(2).jar:?]
        at cz.coffee.skjson.skript.base.Converter$3.fromJson(Converter.java:114) ~[skJson-2.9.shaded(2).jar:?]
        at cz.coffee.skjson.skript.base.Converter$2.fromJson(Converter.java:99) ~[skJson-2.9.shaded(2).jar:?]
        at cz.coffee.skjson.skript.base.Converter$2.fromJson(Converter.java:62) ~[skJson-2.9.shaded(2).jar:?]
        at cz.coffee.skjson.parser.ParserUtil.from(ParserUtil.java:280) ~[skJson-2.9.shaded(2).jar:?]
        at cz.coffee.skjson.skript.base.JsonBase$Elements.get(JsonBase.java:335) ~[skJson-2.9.shaded(2).jar:?]
        at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:101) ~[Skript(3).jar:?]
        at ch.njol.skript.lang.util.ConvertedExpression.getArray(ConvertedExpression.java:165) ~[Skript(3).jar:?]
        at ch.njol.skript.effects.EffChange.execute(EffChange.java:272) ~[Skript(3).jar:?]
        at ch.njol.skript.lang.Effect.run(Effect.java:50) ~[Skript(3).jar:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:62) ~[Skript(3).jar:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:90) ~[Skript(3).jar:?]
        at ch.njol.skript.lang.Trigger.execute(Trigger.java:52) ~[Skript(3).jar:?]
        at ch.njol.skript.lang.function.ScriptFunction.execute(ScriptFunction.java:86) ~[Skript(3).jar:?]
        at ch.njol.skript.lang.function.Function.execute(Function.java:129) ~[Skript(3).jar:?]
        at ch.njol.skript.lang.function.FunctionReference.execute(FunctionReference.java:301) ~[Skript(3).jar:?]
        at ch.njol.skript.lang.function.ExprFunctionCall.get(ExprFunctionCall.java:60) ~[Skript(3).jar:?]
        at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:101) ~[Skript(3).jar:?]
        at ch.njol.skript.lang.util.SimpleExpression.getSingle(SimpleExpression.java:59) ~[Skript(3).jar:?]
        at ch.njol.skript.effects.EffOpenInventory.execute(EffOpenInventory.java:106) ~[Skript(3).jar:?]
        at ch.njol.skript.lang.Effect.run(Effect.java:50) ~[Skript(3).jar:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:62) ~[Skript(3).jar:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:90) ~[Skript(3).jar:?]
        at ch.njol.skript.lang.Trigger.execute(Trigger.java:52) ~[Skript(3).jar:?]
        at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:312) ~[Skript(3).jar:?]
        at ch.njol.skript.command.ScriptCommand.lambda$execute$0(ScriptCommand.java:277) ~[Skript(3).jar:?]
        at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:282) ~[Skript(3).jar:?]
        at ch.njol.skript.command.Commands.handleCommand(Commands.java:193) ~[Skript(3).jar:?]
        at ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:152) ~[Skript(3).jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:git-Paper-174]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.1.jar:git-Paper-174]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.1.jar:git-Paper-174]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2330) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$21(ServerGamePacketListenerImpl.java:2314) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.1.jar:git-Paper-174]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1338) ~[paper-1.20.1.jar:git-Paper-174]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.20.1.jar:git-Paper-174]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1315) ~[paper-1.20.1.jar:git-Paper-174]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1308) ~[paper-1.20.1.jar:git-Paper-174]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1286) ~[paper-1.20.1.jar:git-Paper-174]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1174) ~[paper-1.20.1.jar:git-Paper-174]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-174]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

Damage is not displayed after that

**Comment by cooffeeRequired** [comment]
So when you tried parse item right?
can you provide the code?

**Comment by ghost** [comment]
![image](https://github.com/SkJsonTeam/skJson/assets/130649230/2e9c182d-1d15-4938-8957-4705cc282dcf)
Fixed.
https://skjson.xyz/download
