### ISSUE TITLE
Non-stored requests doesn't work

### ISSUE THREAD

**Issue by kubaczak** [cooffeeRequired/skJson#78]
My code: 
```
command testt:
  trigger:
    make GET request to "https://dummyjson.com/products/1":
      content: {_c}
    broadcast {_c}
```

Console error:

```[19:35:00 ERROR]: #!#!
[19:35:00 ERROR]: #!#! [Skript] Severe Error:
[19:35:00 ERROR]: #!#!
[19:35:00 ERROR]: #!#! Something went horribly wrong with Skript.
[19:35:00 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[19:35:00 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[19:35:00 ERROR]: #!#! Here is full list of them:
[19:35:00 ERROR]: #!#! skript-placeholders v1.5.2 (https://github.com/APickledWalrus/skript-placeholders) skript-reflect v2.4-dev1 (https://github.com/TPGamesNL/skript-reflect) SkJson v2.9.4 (https://www.skjson.xyz/) SkBee v2.18.3 (https://github.com/ShaneBeee/SkBee) skUtilities v0.9.2 (https://tim740.github.io/) SkQuery v4.1.10
[19:35:00 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[19:35:00 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[19:35:00 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[19:35:00 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[19:35:00 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[19:35:00 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[19:35:00 ERROR]: #!#!
[19:35:00 ERROR]: #!#! Stack trace:
[19:35:00 ERROR]: #!#! java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
[19:35:00 ERROR]: #!#!     at SkJson (2).jar//cz.coffee.skjson.skript.request.RequestUtil.validateContent(RequestUtil.java:107)
[19:35:00 ERROR]: #!#!     at SkJson (2).jar//cz.coffee.skjson.skript.request.SecCreateRequest.walk(SecCreateRequest.java:152)
[19:35:00 ERROR]: #!#!     at Skript (4).jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:90)
[19:35:00 ERROR]: #!#!     at Skript (4).jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:52)
[19:35:00 ERROR]: #!#!     at Skript (4).jar//ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:316)
[19:35:00 ERROR]: #!#!     at Skript (4).jar//ch.njol.skript.command.ScriptCommand.lambda$execute$0(ScriptCommand.java:275)
[19:35:00 ERROR]: #!#!     at Skript (4).jar//ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:286)
[19:35:00 ERROR]: #!#!     at Skript (4).jar//ch.njol.skript.command.ScriptCommand.onCommand(ScriptCommand.java:221)
[19:35:00 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[19:35:00 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168)
[19:35:00 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:1001)
[19:35:00 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64)
[19:35:00 ERROR]: #!#!     at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265)
[19:35:00 ERROR]: #!#!     at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:332)
[19:35:00 ERROR]: #!#!     at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:316)
[19:35:00 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2447)
[19:35:00 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$22(PlayerConnection.java:2407)
[19:35:00 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)
[19:35:00 ERROR]: #!#!     at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[19:35:00 ERROR]: #!#!     at net.minecraft.server.TickTask.run(TickTask.java:18)
[19:35:00 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[19:35:00 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[19:35:00 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1365)
[19:35:00 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197)
[19:35:00 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[19:35:00 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1342)
[19:35:00 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1335)
[19:35:00 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[19:35:00 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.p_(MinecraftServer.java:1313)
[19:35:00 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1201)
[19:35:00 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322)
[19:35:00 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[19:35:00 ERROR]: #!#!
[19:35:00 ERROR]: #!#! Version Information:
[19:35:00 ERROR]: #!#!   Skript: 2.7.2 (latest)
[19:35:00 ERROR]: #!#!     Flavor: skriptlang-github
[19:35:00 ERROR]: #!#!     Date: 17:46:44.085781900
[19:35:00 ERROR]: #!#!   Bukkit: 1.20.1-R0.1-SNAPSHOT
[19:35:00 ERROR]: #!#!   Minecraft: 1.20.1
[19:35:00 ERROR]: #!#!   Java: 17.0.8 (Java HotSpot(TM) 64-Bit Server VM 17.0.8+9-LTS-211)
[19:35:00 ERROR]: #!#!   OS: Windows 11 amd64 10.0
[19:35:00 ERROR]: #!#!
[19:35:00 ERROR]: #!#! Server platform: Paper
[19:35:00 ERROR]: #!#!
[19:35:00 ERROR]: #!#! Current node: null
[19:35:00 ERROR]: #!#! Current item: New request section
[19:35:00 ERROR]: #!#! Current trigger: command /testt (simple event) (vote.sk, line 104)
[19:35:00 ERROR]: #!#!
[19:35:00 ERROR]: #!#! Thread: Server thread
[19:35:00 ERROR]: #!#!
[19:35:00 ERROR]: #!#! Language: english
[19:35:00 ERROR]: #!#! Link parse mode: DISABLED
[19:35:00 ERROR]: #!#!
[19:35:00 ERROR]: #!#! End of Error.
[19:35:00 ERROR]: #!#!
```

**Comment by ghost** [comment]
Known issue

**Comment by cooffeeRequired** [comment]
![image](https://github.com/SkJsonTeam/skJson/assets/106232282/03d77842-28a9-4036-9817-e3788641ad96)
Did you mean use content on the save section?

**Comment by cooffeeRequired** [comment]
![image](https://github.com/SkJsonTeam/skJson/assets/106232282/ec77dfc8-9b35-4894-9bda-e1ab50791775)
Basically the raw content means the input body... not the save var at all.

**Comment by cooffeeRequired** [comment]
![image](https://github.com/SkJsonTeam/skJson/assets/106232282/ee7d281d-a857-44ce-ae10-d5f1704e73ba)
Fixed... sanitized the wrong input
