### ISSUE TITLE
Loading the addon in 1.20.6

### ISSUE THREAD

**Issue by RlmUwU** [cooffeeRequired/skJson#94]
I'm trying to load skjson in 1.20.6, but it doesn't work
I get this every time I launch the server, I have the last version of skbee, and it looks like the problem comes from the new way of handling the NBT tags for minecraft, which was updated by skbee but not skjson

```
[09:29:43 INFO]: [SkJson] Enabling SkJson v3.0.7
[09:29:43 ERROR]: Error occurred while enabling SkJson v3.0.7 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at SkJson.jar/com.shanebeestudios.skbee.api.nbt.utils.nmsmappings.ReflectionMethod.<clinit>(ReflectionMethod.java:24) ~[SkJson.jar:?]
        at SkJson.jar/com.shanebeestudios.skbee.api.nbt.NBTContainer.<init>(NBTContainer.java:68) ~[SkJson.jar:?]
        at SkJson.jar/cz.coffee.skjson.api.Config.init(Config.java:284) ~[SkJson.jar:?]
        at SkJson.jar/cz.coffee.skjson.SkJson.onEnable(SkJson.java:39) ~[SkJson.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.20.6.jar:git-Paper-33]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.6.jar:git-Paper-33]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:639) ~[paper-1.20.6.jar:git-Paper-33]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:551) ~[paper-1.20.6.jar:git-Paper-33]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:682) ~[paper-1.20.6.jar:git-Paper-33]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:441) ~[paper-1.20.6.jar:git-Paper-33]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:324) ~[paper-1.20.6.jar:git-Paper-33]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1140) ~[paper-1.20.6.jar:git-Paper-33]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[paper-1.20.6.jar:git-Paper-33]
        at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
        at SkJson.jar/com.shanebeestudios.skbee.api.nbt.utils.MinecraftVersion.getVersion(MinecraftVersion.java:111) ~[SkJson.jar:?]
        at SkJson.jar/com.shanebeestudios.skbee.api.nbt.utils.nmsmappings.ClassWrapper.<init>(ClassWrapper.java:79) ~[SkJson.jar:?]
        at SkJson.jar/com.shanebeestudios.skbee.api.nbt.utils.nmsmappings.ClassWrapper.<init>(ClassWrapper.java:73) ~[SkJson.jar:?]
        at SkJson.jar/com.shanebeestudios.skbee.api.nbt.utils.nmsmappings.ClassWrapper.<clinit>(ClassWrapper.java:21) ~[SkJson.jar:?]
        ... 16 more
[09:29:43 INFO]: [SkJson] Disabling SkJson v3.0.7
[09:29:43 INFO]: [SkJson] JsonWatcher Trying to unregister all watchers!
[09:29:43 INFO]: [SkJson] JsonWatcher Unregistering all watchers was successfully!
[09:29:43 INFO]: [SkJson] Goodbye! SkJson is Disabled!
```

**Comment by cooffeeRequired** [comment]
It's related to the SkBee dependency, i working on it rn.

**Comment by cooffeeRequired** [comment]
```
[05:35:59] [ServerMain/INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[05:36:00] [ServerMain/INFO]: Loaded 1175 recipes
[05:36:00] [ServerMain/INFO]: Loaded 1276 advancements
[05:36:01] [Server thread/INFO]: Starting minecraft server version 1.20.6
[05:36:01] [Server thread/INFO]: Loading properties
[05:36:01] [Server thread/INFO]: This server is running Purpur version git-Purpur-2193 (MC: 1.20.6) (Implementing API version 1.20.6-R0.1-SNAPSHOT) (Git: 33a31b0 on HEAD)
[05:36:01] [Server thread/INFO]: Server Ping Player Sample Count: 12
[05:36:01] [Server thread/INFO]: Using 4 threads for Netty based IO
[05:36:02] [Server thread/INFO]: [ChunkTaskScheduler] Chunk system is using 1 I/O threads, 3 worker threads, and gen parallelism of 3 threads
[05:36:02] [Server thread/INFO]: Default game type: SURVIVAL
[05:36:02] [Server thread/INFO]: Generating keypair
[05:36:02] [Server thread/INFO]: Starting Minecraft server on *:25564
[05:36:03] [Server thread/INFO]: Using default channel type
[05:36:03] [Server thread/INFO]: Paper: Using Java compression from Velocity.
[05:36:03] [Server thread/INFO]: Paper: Using Java cipher from Velocity.
[05:36:03] [Server thread/INFO]: [SpigotLibraryLoader] [SkJson] Loading 2 libraries... please wait
[05:36:03] [Server thread/INFO]: [SpigotLibraryLoader] [SkJson] Loaded library D:\Git\mc_server\libraries\org\glassfish\jersey\core\jersey-server\2.34\jersey-server-2.34.jar
[05:36:03] [Server thread/INFO]: [SpigotLibraryLoader] [SkJson] Loaded library D:\Git\mc_server\libraries\org\glassfish\jersey\core\jersey-common\2.34\jersey-common-2.34.jar
[05:36:03] [Server thread/INFO]: [SpigotLibraryLoader] [SkJson] Loaded library D:\Git\mc_server\libraries\org\glassfish\hk2\osgi-resource-locator\1.0.3\osgi-resource-locator-1.0.3.jar
[05:36:03] [Server thread/INFO]: [SpigotLibraryLoader] [SkJson] Loaded library D:\Git\mc_server\libraries\org\glassfish\jersey\core\jersey-client\2.34\jersey-client-2.34.jar
[05:36:03] [Server thread/INFO]: [SpigotLibraryLoader] [SkJson] Loaded library D:\Git\mc_server\libraries\jakarta\ws\rs\jakarta.ws.rs-api\2.1.6\jakarta.ws.rs-api-2.1.6.jar
[05:36:03] [Server thread/INFO]: [SpigotLibraryLoader] [SkJson] Loaded library D:\Git\mc_server\libraries\jakarta\annotation\jakarta.annotation-api\1.3.5\jakarta.annotation-api-1.3.5.jar
[05:36:03] [Server thread/INFO]: [SpigotLibraryLoader] [SkJson] Loaded library D:\Git\mc_server\libraries\org\glassfish\hk2\external\jakarta.inject\2.6.1\jakarta.inject-2.6.1.jar
[05:36:03] [Server thread/INFO]: [SpigotLibraryLoader] [SkJson] Loaded library D:\Git\mc_server\libraries\jakarta\validation\jakarta.validation-api\2.0.2\jakarta.validation-api-2.0.2.jar
[05:36:03] [Server thread/INFO]: [SpigotLibraryLoader] [SkJson] Loaded library D:\Git\mc_server\libraries\org\eclipse\jetty\jetty-client\12.0.1\jetty-client-12.0.1.jar
[05:36:03] [Server thread/INFO]: [SpigotLibraryLoader] [SkJson] Loaded library D:\Git\mc_server\libraries\org\eclipse\jetty\jetty-http\12.0.1\jetty-http-12.0.1.jar
[05:36:03] [Server thread/INFO]: [SpigotLibraryLoader] [SkJson] Loaded library D:\Git\mc_server\libraries\org\eclipse\jetty\jetty-util\12.0.1\jetty-util-12.0.1.jar
[05:36:03] [Server thread/INFO]: [SpigotLibraryLoader] [SkJson] Loaded library D:\Git\mc_server\libraries\org\eclipse\jetty\jetty-io\12.0.1\jetty-io-12.0.1.jar
[05:36:03] [Server thread/INFO]: [SpigotLibraryLoader] [SkJson] Loaded library D:\Git\mc_server\libraries\org\eclipse\jetty\jetty-alpn-client\12.0.1\jetty-alpn-client-12.0.1.jar
[05:36:03] [Server thread/INFO]: [SpigotLibraryLoader] [SkJson] Loaded library D:\Git\mc_server\libraries\org\slf4j\slf4j-api\2.0.7\slf4j-api-2.0.7.jar
[05:36:03] [Server thread/INFO]: [Skript] Loading server plugin Skript v2.8.5
[05:36:03] [Server thread/INFO]: [spark] Loading server plugin spark v1.10.66
[05:36:03] [Server thread/INFO]: [SkJson] Loading server plugin SkJson v3.1.0
[05:36:03] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[05:36:03] [Server thread/WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[05:36:03] [Server thread/WARN]: The server will make no attempt to authenticate usernames. Beware.
[05:36:03] [Server thread/WARN]: While this makes the game possible to play without internet access, it also opens up the ability for hackers to connect with any username they choose.
[05:36:03] [Server thread/WARN]: To change this, set "online-mode" to "true" in the server.properties file.
[05:36:03] [Server thread/INFO]: Preparing level "world"
[05:36:04] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[05:36:05] [Server thread/INFO]: Time elapsed: 867 ms
[05:36:05] [Server thread/INFO]: Preparing start region for dimension minecraft:the_nether
[05:36:05] [Server thread/INFO]: Time elapsed: 138 ms
[05:36:05] [Server thread/INFO]: Preparing start region for dimension minecraft:the_end
[05:36:05] [Server thread/INFO]: Time elapsed: 109 ms
[05:36:05] [Server thread/INFO]: [Skript] Enabling Skript v2.8.5
[05:36:06] [ForkJoinPool.commonPool-worker-1/INFO]: [Skript] You're currently running the latest stable version of Skript.
[05:36:12] [Server thread/INFO]: [Skript] Loaded 233068 aliases in 6343ms
[05:36:13] [Server thread/INFO]: [Skript]  ~ created by & © Peter Güttinger aka Njol ~
[05:36:13] [Server thread/INFO]: [spark] Enabling spark v1.10.66
[05:36:14] [Server thread/INFO]: [spark] Using Paper ServerTickStartEvent for tick monitoring
[05:36:14] [Server thread/INFO]: [spark] Starting background profiler...
[05:36:14] [Server thread/INFO]: [spark] The async-profiler engine is not supported for your os/arch (windows11/amd64), so the built-in Java engine will be used instead.
[05:36:14] [Server thread/INFO]: [SkJson] Enabling SkJson v3.1.0
[05:36:14] [Server thread/INFO]: [SkJson] NBTAPI  NMS support 'MC1_20_R4' loaded!
[05:36:14] [Server thread/INFO]: [SkJson] NBTAPI  Was loaded successfully.
[05:36:14] [Server thread/INFO]: [SkJson] Metrics  Was loaded successfully.
[05:36:14] [Server thread/INFO]: [SkJson] Skript was found and initialized.
[05:36:14] [Server thread/INFO]: [SkJson] JsonWatcher was initialized.
[05:36:15] [Server thread/INFO]: [SkJson] You're running on non-public version, so checking is not necessary v3.1.0!
[05:36:15] [HttpClient@1b429cdf-92/INFO]: [SkJson] Requests : GET request was send to 'https://api.github.com/repositories/555255955/releases/latest' and takes 00h 00m 00s.591ms'591000μs
[05:36:15] [Server thread/INFO]: [SkJson] Registered elements..
[05:36:15] [Server thread/INFO]: [SkJson]    - Registered Sections 1
[05:36:15] [Server thread/INFO]: [SkJson]    - Registered Events 1
[05:36:15] [Server thread/INFO]: [SkJson]    - Registered Structures 0
[05:36:15] [Server thread/INFO]: [SkJson]    - Registered Functions 4
[05:36:15] [Server thread/INFO]: [SkJson]    - Registered Effects 10
[05:36:15] [Server thread/INFO]: [SkJson]    - Registered Expressions 18
[05:36:15] [Server thread/INFO]: [SkJson]    - Registered Conditions 5
[05:36:15] [Server thread/INFO]: [SkJson] Hurray! SkJson is enabled.
[05:36:15] [Server thread/INFO]: Running delayed init tasks
[05:36:15] [Server thread/INFO]: [Skript] Loading variables...
[05:36:15] [Server thread/INFO]: [Skript] Loaded 19 variables in 0.0 seconds
[05:36:15] [HttpClient@5afbf894-104/INFO]: [SkJson] Requests : GET request was send to 'https://helldiverstrainingmanual.com/api/v1/war/campaign' and takes 00h 00m 00s.217ms'217000μs
[05:36:15] [Server thread/INFO]: [{"planetIndex":125,"name":"Fenrir III","faction":"Terminids","players":13819,"health":390537,"maxHealth":450000,"percentage":13.213999999999999,"defense":true,"majorOrder":false,"biome":{"slug":"moon","description":"A rocky, lonely moon with extremely valuable mineral deposits underneath the surface."},"expireDateTime":1715267766.142},{"planetIndex":194,"name":"Lesath","faction":"Automatons","players":4209,"health":284567,"maxHealth":300000,"percentage":5.144333333333336,"defense":true,"majorOrder":false,"biome":{"slug":"icemoss","description":"Ice and moss-covered rock can be found across most of the surface of this planet."},"expireDateTime":1715267806.142},{"planetIndex":80,"name":"Veld","faction":"Terminids","players":67844,"health":909514,"maxHealth":1000000,"percentage":9.048599999999993,"defense":false,"majorOrder":false,"biome":{"slug":"rainforest","description":"The strange subversion of photosynthesis that sustains the oddly-hued flora that flourishes on this planet remains an intriguing mystery to Super Earth's greatest exo-biologists."},"expireDateTime":null},{"planetIndex":129,"name":"Acamar IV","faction":"Terminids","players":22004,"health":998867,"maxHealth":1000000,"percentage":0.1132999999999953,"defense":false,"majorOrder":false,"biome":{"slug":"highlands","description":"Rocky outcroppings punctuate fields of tall grass in a planet dominated by misty highland terrain."},"expireDateTime":null},{"planetIndex":156,"name":"Charbal-VII","faction":"Automatons","players":222,"health":1000000,"maxHealth":1000000,"percentage":0,"defense":false,"majorOrder":false,"biome":{"slug":"toxic","description":"Dense, toxic fumes from deep within the planet's crust seep out of cracks in the earth and coat the ground in a sickly haze."},"expireDateTime":null},{"planetIndex":158,"name":"Choepessa IV","faction":"Automatons","players":1000,"health":1000000,"maxHealth":1000000,"percentage":0,"defense":false,"majorOrder":false,"biome":{"slug":"icemoss","description":"Ice and moss-covered rock can be found across most of the surface of this planet."},"expireDateTime":null},{"planetIndex":160,"name":"Chort Bay","faction":"Automatons","players":313,"health":1000000,"maxHealth":1000000,"percentage":0,"defense":false,"majorOrder":false,"biome":{"slug":"toxic","description":"Dense, toxic fumes from deep within the planet's crust seep out of cracks in the earth and coat the ground in a sickly haze."},"expireDateTime":null},{"planetIndex":34,"name":"Hellmire","faction":"Terminids","players":2139,"health":1000000,"maxHealth":1000000,"percentage":0,"defense":false,"majorOrder":false,"biome":{"slug":"desolate","description":"Scorching temperatures, high winds, and low precipitation cause a near-constant cycle of fires to sweep this planet, punctuated by short bursts of lush rebirth between infernos."},"expireDateTime":null},{"planetIndex":198,"name":"Marfark","faction":"Automatons","players":2336,"health":1000000,"maxHealth":1000000,"percentage":0,"defense":false,"majorOrder":false,"biome":{"slug":"winter","description":"Submerged in eternal winter, this world's frosty peaks glimmer in the light of its too-distant star."},"expireDateTime":null},{"planetIndex":201,"name":"Meissa","faction":"Automatons","players":1081,"health":1000000,"maxHealth":1000000,"percentage":0,"defense":false,"majorOrder":false,"biome":{"slug":"jungle","description":"Abundant with life, this wet planet is covered in deep oceans, thick forests, and tall grasses."},"expireDateTime":null},{"planetIndex":203,"name":"Menkent","faction":"Automatons","players":2856,"health":1000000,"maxHealth":1000000,"percentage":0,"defense":false,"majorOrder":false,"biome":{"slug":"desolate","description":"Scorching temperatures, high winds, and low precipitation cause a near-constant cycle of fires to sweep this planet, punctuated by short bursts of lush rebirth between infernos."},"expireDateTime":null},{"planetIndex":214,"name":"Pandion-XXIV","faction":"Terminids","players":4103,"health":1000000,"maxHealth":1000000,"percentage":0,"defense":false,"majorOrder":false,"biome":{"slug":"swamp","description":"The lifeless grey of this planet is interrupted only by the violet flowers that grow from strange, parasitic outcroppings."},"expireDateTime":null},{"planetIndex":115,"name":"Penta","faction":"Automatons","players":1043,"health":1000000,"maxHealth":1000000,"percentage":0,"defense":false,"majorOrder":false,"biome":{"slug":"swamp","description":"The lifeless grey of this planet is interrupted only by the violet flowers that grow from strange, parasitic outcroppings."},"expireDateTime":null}]
[05:36:15] [Server thread/INFO]: [{"id32":738112495,"progress":[1,1,0,0],"expiresIn":124519,"setting":{"type":4,"overrideTitle":"MAJOR ORDER","overrideBrief":"The Supercolony has caused sudden outbreaks on multiple planets. They must be contained immediately.","taskDescription":"Liberate all designated planets.","tasks":[{"type":11,"values":[1,1,79],"valueTypes":[3,11,12]},{"type":11,"values":[1,1,127],"valueTypes":[3,11,12]},{"type":11,"values":[1,1,80],"valueTypes":[3,11,12]},{"type":11,"values":[1,1,129],"valueTypes":[3,11,12]}],"reward":{"type":1,"id32":897894480,"amount":40},"flags":0}}]
[05:36:15] [HttpClient@1bdbbc36-116/INFO]: [SkJson] Requests : GET request was send to 'https://helldiverstrainingmanual.com/api/v1/war/major-orders' and takes 00h 00m 00s.104ms'104000μs
[05:36:15] [Server thread/INFO]: [Skript] All scripts loaded without errors.
[05:36:15] [Server thread/INFO]: [Skript] Loaded 1 script with a total of 1 structure in 0.47 seconds
[05:36:15] [Server thread/INFO]: [Skript] Finished loading.
[05:36:15] [Server thread/INFO]: Done (14.921s)! For help, type "help"
[05:36:21] [Server thread/INFO]: Stopping server
[05:36:21] [Server thread/INFO]: [SkJson] Disabling SkJson v3.1.0
[05:36:21] [Server thread/INFO]: [SkJson] JsonWatcher Trying to unregister all watchers!
[05:36:21] [Server thread/INFO]: [SkJson] JsonWatcher Unregistering all watchers was successfully!
[05:36:21] [Server thread/INFO]: [SkJson] Goodbye! SkJson is Disabled!
[05:36:21] [Server thread/INFO]: [spark] Disabling spark v1.10.66
[05:36:21] [Server thread/INFO]: [Skript] Disabling Skript v2.8.5
[05:36:21] [Server thread/INFO]: Saving players
[05:36:21] [Server thread/INFO]: Saving worlds
[05:36:21] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:overworld
[05:36:21] [Server thread/INFO]: [ChunkHolderManager] Waiting 60s for chunk system to halt for world 'world'
[05:36:21] [Server thread/INFO]: [ChunkHolderManager] Halted chunk system for world 'world'
[05:36:21] [Server thread/INFO]: [ChunkHolderManager] Saving all chunkholders for world 'world'
[05:36:22] [Server thread/INFO]: [ChunkHolderManager] Saved 49 block chunks, 49 entity chunks, 0 poi chunks in world 'world' in 0,26s
[05:36:22] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[05:36:22] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world_nether]'/minecraft:the_nether
[05:36:22] [Server thread/INFO]: [ChunkHolderManager] Waiting 60s for chunk system to halt for world 'world_nether'
[05:36:22] [Server thread/INFO]: [ChunkHolderManager] Halted chunk system for world 'world_nether'
[05:36:22] [Server thread/INFO]: [ChunkHolderManager] Saving all chunkholders for world 'world_nether'
[05:36:22] [Server thread/INFO]: [ChunkHolderManager] Saved 49 block chunks, 49 entity chunks, 0 poi chunks in world 'world_nether' in 0,17s
[05:36:22] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[05:36:22] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world_the_end]'/minecraft:the_end
[05:36:22] [Server thread/INFO]: [ChunkHolderManager] Waiting 60s for chunk system to halt for world 'world_the_end'
[05:36:22] [Server thread/INFO]: [ChunkHolderManager] Halted chunk system for world 'world_the_end'
[05:36:22] [Server thread/INFO]: [ChunkHolderManager] Saving all chunkholders for world 'world_the_end'
[05:36:22] [Server thread/INFO]: [ChunkHolderManager] Saved 49 block chunks, 49 entity chunks, 0 poi chunks in world 'world_the_end' in 0,12s
[05:36:22] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[05:36:22] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[05:36:22] [Server thread/INFO]: Flushing Chunk IO
[05:36:22] [Server thread/INFO]: Closing Thread Pool
[05:36:22] [Server thread/INFO]: Closing Server
```

[SkJson-patch.zip](https://github.com/cooffeeRequired/skJson/files/15257262/SkJson-patch.zip)
![image](https://github.com/cooffeeRequired/skJson/assets/106232282/79ac38c2-8b54-405c-8db0-f4c3d763b3d2)

Issue already fixed..
